%
% Copyright 2017 United States Government as represented by the
% Administrator of the National Aeronautics and Space Administration.
% All Rights Reserved.
% 
% This file is available under the terms of the NASA Open Source Agreement
% (NOSA). You should have received a copy of this agreement with the
% Kepler source code; see the file NASA-OPEN-SOURCE-AGREEMENT.doc.
% 
% No Warranty: THE SUBJECT SOFTWARE IS PROVIDED "AS IS" WITHOUT ANY
% WARRANTY OF ANY KIND, EITHER EXPRESSED, IMPLIED, OR STATUTORY,
% INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY THAT THE SUBJECT SOFTWARE
% WILL CONFORM TO SPECIFICATIONS, ANY IMPLIED WARRANTIES OF
% MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR FREEDOM FROM
% INFRINGEMENT, ANY WARRANTY THAT THE SUBJECT SOFTWARE WILL BE ERROR
% FREE, OR ANY WARRANTY THAT DOCUMENTATION, IF PROVIDED, WILL CONFORM
% TO THE SUBJECT SOFTWARE. THIS AGREEMENT DOES NOT, IN ANY MANNER,
% CONSTITUTE AN ENDORSEMENT BY GOVERNMENT AGENCY OR ANY PRIOR RECIPIENT
% OF ANY RESULTS, RESULTING DESIGNS, HARDWARE, SOFTWARE PRODUCTS OR ANY
% OTHER APPLICATIONS RESULTING FROM USE OF THE SUBJECT SOFTWARE.
% FURTHER, GOVERNMENT AGENCY DISCLAIMS ALL WARRANTIES AND LIABILITIES
% REGARDING THIRD-PARTY SOFTWARE, IF PRESENT IN THE ORIGINAL SOFTWARE,
% AND DISTRIBUTES IT "AS IS."
% 
% Waiver and Indemnity: RECIPIENT AGREES TO WAIVE ANY AND ALL CLAIMS
% AGAINST THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND
% SUBCONTRACTORS, AS WELL AS ANY PRIOR RECIPIENT. IF RECIPIENT'S USE OF
% THE SUBJECT SOFTWARE RESULTS IN ANY LIABILITIES, DEMANDS, DAMAGES,
% EXPENSES OR LOSSES ARISING FROM SUCH USE, INCLUDING ANY DAMAGES FROM
% PRODUCTS BASED ON, OR RESULTING FROM, RECIPIENT'S USE OF THE SUBJECT
% SOFTWARE, RECIPIENT SHALL INDEMNIFY AND HOLD HARMLESS THE UNITED
% STATES GOVERNMENT, ITS CONTRACTORS AND SUBCONTRACTORS, AS WELL AS ANY
% PRIOR RECIPIENT, TO THE EXTENT PERMITTED BY LAW. RECIPIENT'S SOLE
% REMEDY FOR ANY SUCH MATTER SHALL BE THE IMMEDIATE, UNILATERAL
% TERMINATION OF THIS AGREEMENT.
%
mjdStartq0 = 54953.02;
mjdEndq0 =   54954;
mjdStartq1 = 54964.00077704;  
mjdEndq1 =   54966.49144170;
mjdStartq2 = 55054.01;
mjdEndq2   = 55058.98;
mjdStartq3 = 55098.71;
mjdEndq3   = 55103.01;
mjdStartq4 = 55186.86;
mjdEndq4   = 55189.00;
mjdStartq5 = 55284.00;
mjdEndq5   = 55286.40;
mjdStartq6 = 55372.00;
mjdEndq6   = 55380.40;
mjdStartq7 = 55463.00;
mjdEndq7=55495.40;
q0targetListSetName= 'cdpp_v1_verification_lc';
q1targetListSetName= 'quarter1_spring2009_lc_v2' ;
q2targetListSetName= 'quarter2_summer2009_lc';
q3targetListSetName= 'quarter3_fall2009_lc_v3';
q4targetListSetName= 'quarter4_winter2009_lc';
q5targetListSetName='quarter5_spring2010_lc_v2';
q6targetListSetName='quarter6_summer2010_trimmed_v3_lc';
startCadenceq0 = 568;
endCadenceq0 = 569;
startCadenceq1 = 1105;
endCadenceq1 = 1106;
startCadenceq2 = 4473;
endCadenceq2 = 4474;
startCadenceq3 =7404;
endCadenceq3 = 7405;
startCadenceq4 = 11914;
endCadenceq4 = 11915;
startCadenceq5 = 16373; 
endCadenceq5 = 16374;
startCadenceq6 =21069;
endCadenceq6 =21070;
startCadenceq7=25509;
endCadenceq7=25510;
startCadence=1105;
endCadence = 1110;



