function [RptgenML_CReport1] = buildpmd
%BUILDPMD
% 
% Copyright 2017 United States Government as represented by the
% Administrator of the National Aeronautics and Space Administration.
% All Rights Reserved.
% 
% NASA acknowledges the SETI Institute's primary role in authoring and
% producing the Kepler Data Processing Pipeline under Cooperative
% Agreement Nos. NNA04CC63A, NNX07AD96A, NNX07AD98A, NNX11AI13A,
% NNX11AI14A, NNX13AD01A & NNX13AD16A.
% 
% This file is available under the terms of the NASA Open Source Agreement
% (NOSA). You should have received a copy of this agreement with the
% Kepler source code; see the file NASA-OPEN-SOURCE-AGREEMENT.doc.
% 
% No Warranty: THE SUBJECT SOFTWARE IS PROVIDED "AS IS" WITHOUT ANY
% WARRANTY OF ANY KIND, EITHER EXPRESSED, IMPLIED, OR STATUTORY,
% INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY THAT THE SUBJECT SOFTWARE
% WILL CONFORM TO SPECIFICATIONS, ANY IMPLIED WARRANTIES OF
% MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR FREEDOM FROM
% INFRINGEMENT, ANY WARRANTY THAT THE SUBJECT SOFTWARE WILL BE ERROR
% FREE, OR ANY WARRANTY THAT DOCUMENTATION, IF PROVIDED, WILL CONFORM
% TO THE SUBJECT SOFTWARE. THIS AGREEMENT DOES NOT, IN ANY MANNER,
% CONSTITUTE AN ENDORSEMENT BY GOVERNMENT AGENCY OR ANY PRIOR RECIPIENT
% OF ANY RESULTS, RESULTING DESIGNS, HARDWARE, SOFTWARE PRODUCTS OR ANY
% OTHER APPLICATIONS RESULTING FROM USE OF THE SUBJECT SOFTWARE.
% FURTHER, GOVERNMENT AGENCY DISCLAIMS ALL WARRANTIES AND LIABILITIES
% REGARDING THIRD-PARTY SOFTWARE, IF PRESENT IN THE ORIGINAL SOFTWARE,
% AND DISTRIBUTES IT "AS IS."
% 
% Waiver and Indemnity: RECIPIENT AGREES TO WAIVE ANY AND ALL CLAIMS
% AGAINST THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND
% SUBCONTRACTORS, AS WELL AS ANY PRIOR RECIPIENT. IF RECIPIENT'S USE OF
% THE SUBJECT SOFTWARE RESULTS IN ANY LIABILITIES, DEMANDS, DAMAGES,
% EXPENSES OR LOSSES ARISING FROM SUCH USE, INCLUDING ANY DAMAGES FROM
% PRODUCTS BASED ON, OR RESULTING FROM, RECIPIENT'S USE OF THE SUBJECT
% SOFTWARE, RECIPIENT SHALL INDEMNIFY AND HOLD HARMLESS THE UNITED
% STATES GOVERNMENT, ITS CONTRACTORS AND SUBCONTRACTORS, AS WELL AS ANY
% PRIOR RECIPIENT, TO THE EXTENT PERMITTED BY LAW. RECIPIENT'S SOLE
% REMEDY FOR ANY SUCH MATTER SHALL BE THE IMMEDIATE, UNILATERAL
% TERMINATION OF THIS AGREEMENT.
%
 
%  Auto-generated by MATLAB on 20-Nov-2009 15:06:03
 
% Create RptgenML.CReport
RptgenML_CReport1 = RptgenML.CReport('RptFileName',...
'/path/to/matlab/ppa/pmd/mfiles/pmd.rpt',...
'Stylesheet','default-fo',...
'DirectoryType','pwd');
% setedit(RptgenML_CReport1);
 
% Create rptgen.cfr_titlepage
rptgen_cfr_titlepage1 = rptgen.cfr_titlepage('AuthorMode','none',...
'Subtitle','PPA Metric Determination Processing Report',...
'Title','Photometer Performance Assessment');
setParent(rptgen_cfr_titlepage1,RptgenML_CReport1);
 
% Create rptgen.cfr_section
rptgen_cfr_section1 = rptgen.cfr_section('SectionTitle','General Information');
setParent(rptgen_cfr_section1,RptgenML_CReport1);
 
% Create rptgen.cml_eval
rptgen_cml_eval1 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['reportDateNum = now ;',sprintf('\n'),'ccdModule = pmdInputStruct.ccdModule ;',sprintf('\n'),'ccdOutput = pmdInputStruct.ccdOutput ;',sprintf('\n'),'tab{1,1} = ''Generated:'' ; ',sprintf('\n'),'tab{1,2} = local_time_to_utc(reportDateNum,31) ;',sprintf('\n'),'tab{2,1} = ''Module:'' ;',sprintf('\n'),'tab{2,2} = ''ppa'' ;',sprintf('\n'),'tab{3,1} = ''CCD Module:'' ;',sprintf('\n'),'tab{3,2} = ccdModule ;',sprintf('\n'),'tab{4,1} = ''CCD Output:'' ;',sprintf('\n'),'tab{4,2} = ccdOutput ;']);
setParent(rptgen_cml_eval1,rptgen_cfr_section1);
 
% Create rptgen.cfr_table
rptgen_cfr_table1 = rptgen.cfr_table('numHeaderRows',0,'isBorder',false,'isPgwide',false,...
'Source','tab');
setParent(rptgen_cfr_table1,rptgen_cfr_section1);
 
% Create rptgen.cfr_section
rptgen_cfr_section2 = rptgen.cfr_section('SectionTitle','Inputs');
setParent(rptgen_cfr_section2,RptgenML_CReport1);
 
% Create rptgen.cml_eval
rptgen_cml_eval2 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['clear tab ;',sprintf('\n'),'tab = cell(8,2)',sprintf('\n'),'tab{1,1} = ''Total Number of Cadences'' ;',sprintf('\n'),'tab{2,1} = ''Number of Gapped Cadences'' ;',sprintf('\n'),'tab{3,1} = ''mjd Mid-Time of First Cadence'' ;',sprintf('\n'),'tab{4,1} = ''mjd Mid-Time of Last Cadence'' ;',sprintf('\n'),'tab{5,1} = ''UTC Mid-Time of First Cadence'' ;',sprintf('\n'),'tab{6,1} = ''UTC Mid-Time of Last Cadence'' ;',sprintf('\n'),'tab{7,1} = ''Cadence Number of First Cadence'' ;',sprintf('\n'),'tab{8,1} = ''Cadence Number of Last Cadence'' ;',sprintf('\n'),'',sprintf('\n'),'%',sprintf('\n'),'',sprintf('\n'),'mjd1 = min(pmdInputStruct.cadenceTimes.midTimestamps) ;',sprintf('\n'),'mjd2 = max(pmdInputStruct.cadenceTimes.midTimestamps) ;',sprintf('\n'),'minTime = mjd_to_utc(mjd1,31) ;',sprintf('\n'),'maxTime = mjd_to_utc(mjd2,31) ;',sprintf('\n'),'tab{1,2} = length(pmdInputStruct.cadenceTimes.midTimestamps) ;',sprintf('\n'),'tab{2,2} = length(find(pmdInputStruct.cadenceTimes.gapIndicators==1)) ;',sprintf('\n'),'tab{3,2} = mjd1 ;',sprintf('\n'),'tab{4,2} = mjd2 ;',sprintf('\n'),'tab{5,2} = minTime ;',sprintf('\n'),'tab{6,2} = maxTime ;',sprintf('\n'),'tab{7,2} = min(pmdInputStruct.cadenceTimes.cadenceNumbers) ;',sprintf('\n'),'tab{8,2} = max(pmdInputStruct.cadenceTimes.cadenceNumbers) ;']);
setParent(rptgen_cml_eval2,rptgen_cfr_section2);
 
% Create rptgen.cfr_table
rptgen_cfr_table2 = rptgen.cfr_table('numHeaderRows',0,'Source','tab');
setParent(rptgen_cfr_table2,rptgen_cfr_section2);
 
% Create rptgen.cml_eval
rptgen_cml_eval3 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString','clear tab');
setParent(rptgen_cml_eval3,rptgen_cfr_section2);
 
% Create rptgen.cfr_section
rptgen_cfr_section3 = rptgen.cfr_section('SectionTitle','PMD Metrics Summary');
setParent(rptgen_cfr_section3,RptgenML_CReport1);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph1 = rptgen.cfr_paragraph;
setParent(rptgen_cfr_paragraph1,rptgen_cfr_section3);
 
% Create rptgen.cfr_text
rptgen_cfr_text1 = rptgen.cfr_text('isLiteral',true,'Content','');
setParent(rptgen_cfr_text1,rptgen_cfr_paragraph1);
 
% Create rptgen.cfr_section
rptgen_cfr_section4 = rptgen.cfr_section('SectionTitle','Tracking Summary Display');
setParent(rptgen_cfr_section4,rptgen_cfr_section3);
 
% Create rptgen.cml_eval
rptgen_cml_eval4 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['figure ;',sprintf('\n'),'pmd_plot_track_trend_summary(pmdOutputStruct.report,...',sprintf('\n'),'   ''trackAlertLevel'','' '') ;',sprintf('\n'),'',sprintf('\n'),'h = gcf ;',sprintf('\n'),'set(h,''Position'',[100 100 760 700]) ;',sprintf('\n'),'fileName = pmd_get_plot_filename(''trackDashboard'', ...',sprintf('\n'),'   ccdModule,ccdOutput,reportDateNum ) ;',sprintf('\n'),'saveas(h,fileName) ;',sprintf('\n'),'fileNameFull = fullfile(pwd,fileName) ;',sprintf('\n'),'fileNameFull = [fileNameFull,''.fig''] ;']);
setParent(rptgen_cml_eval4,rptgen_cfr_section4);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph2 = rptgen.cfr_paragraph;
setParent(rptgen_cfr_paragraph2,rptgen_cfr_section4);
 
% Create rptgen.cfr_link
rptgen_cfr_link1 = rptgen.cfr_link('LinkText','Open Figure in Matlab',...
'LinkID','%<fileNameFull>',...
'LinkType','ulink');
setParent(rptgen_cfr_link1,rptgen_cfr_paragraph2);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap1 = rptgen_hg.chg_fig_snap('ImageFormat','jpeg90');
setParent(rptgen_hg_chg_fig_snap1,rptgen_cfr_paragraph2);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph3 = rptgen.cfr_paragraph;
setParent(rptgen_cfr_paragraph3,rptgen_cfr_section4);
 
% Create rptgen.cfr_text
rptgen_cfr_text2 = rptgen.cfr_text('Content',...
['PPA Metric Determination (PMD) Tracking Alerts.  The color coding of the boxes',sprintf('\n'),'indicates the following:']);
setParent(rptgen_cfr_text2,rptgen_cfr_paragraph3);
 
% Create rptgen.cml_eval
rptgen_cml_eval5 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['bulletList = cell(4) ;',sprintf('\n'),'bulletList{1} = ''Green:  Metric is within all bounds at all times'' ;',sprintf('\n'),'bulletList{2} = ''Yellow: Metric exceeds adaptive bounds'' ;',sprintf('\n'),'bulletList{3} = ''Red:    Metric exceeds fixed bounds'' ;',sprintf('\n'),'bulletList{4} = ''Cyan:   Metric information is missing'' ;']);
setParent(rptgen_cml_eval5,rptgen_cfr_paragraph3);
 
% Create rptgen.cfr_list
rptgen_cfr_list1 = rptgen.cfr_list('Source','bulletList');
setParent(rptgen_cfr_list1,rptgen_cfr_paragraph3);
 
% Create rptgen.cml_eval
rptgen_cml_eval6 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['close(h) ;',sprintf('\n'),'clear bulletList h fileName fileNameFull ;']);
setParent(rptgen_cml_eval6,rptgen_cfr_paragraph3);
 
% Create rptgen.cfr_text
rptgen_cfr_text3 = rptgen.cfr_text('isLiteral',true,'Content','');
setParent(rptgen_cfr_text3,rptgen_cfr_paragraph3);
 
% Create rptgen.cfr_section
rptgen_cfr_section5 = rptgen.cfr_section('SectionTitle','Trending Summary Display');
setParent(rptgen_cfr_section5,rptgen_cfr_section3);
 
% Create rptgen.cml_eval
rptgen_cml_eval7 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['figure ;',sprintf('\n'),'pmd_plot_track_trend_summary(pmdOutputStruct.report,...',sprintf('\n'),'   ''trendAlertLevel'','' '') ;',sprintf('\n'),'h = gcf ;',sprintf('\n'),'set(h,''Position'',[100 100 760 700]) ;',sprintf('\n'),'fileName = pmd_get_plot_filename(''trendDashboard'', ...',sprintf('\n'),'   ccdModule,ccdOutput,reportDateNum ) ;',sprintf('\n'),'saveas(h,fileName) ;',sprintf('\n'),'fileNameFull = fullfile(pwd,fileName) ;',sprintf('\n'),'fileNameFull = [fileNameFull,''.fig''] ;']);
setParent(rptgen_cml_eval7,rptgen_cfr_section5);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph4 = rptgen.cfr_paragraph;
setParent(rptgen_cfr_paragraph4,rptgen_cfr_section5);
 
% Create rptgen.cfr_link
rptgen_cfr_link2 = rptgen.cfr_link('LinkText','Open Figure in Matlab',...
'LinkID','%<fileNameFull>',...
'LinkType','ulink');
setParent(rptgen_cfr_link2,rptgen_cfr_paragraph4);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap2 = rptgen_hg.chg_fig_snap('ImageFormat','jpeg90');
setParent(rptgen_hg_chg_fig_snap2,rptgen_cfr_paragraph4);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph5 = rptgen.cfr_paragraph;
setParent(rptgen_cfr_paragraph5,rptgen_cfr_section5);
 
% Create rptgen.cfr_text
rptgen_cfr_text4 = rptgen.cfr_text('Content',...
['PPA Metric Determination (PMD) Trending Alerts.  The color coding of the boxes',sprintf('\n'),'indicates the following:']);
setParent(rptgen_cfr_text4,rptgen_cfr_paragraph5);
 
% Create rptgen.cml_eval
rptgen_cml_eval8 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['bulletList = cell(4) ;',sprintf('\n'),'bulletList{1} = ''Green:  Metric is within all bounds at all times'' ;',sprintf('\n'),'bulletList{2} = ''Yellow: Metric exceeds adaptive bounds'' ;',sprintf('\n'),'bulletList{3} = ''Red:    Metric exceeds fixed bounds'' ;',sprintf('\n'),'bulletList{4} = ''Cyan:   Metric information is missing'' ;']);
setParent(rptgen_cml_eval8,rptgen_cfr_paragraph5);
 
% Create rptgen.cfr_list
rptgen_cfr_list2 = rptgen.cfr_list('Source','bulletList');
setParent(rptgen_cfr_list2,rptgen_cfr_paragraph5);
 
% Create rptgen.cml_eval
rptgen_cml_eval9 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['close(h) ;',sprintf('\n'),'clear bulletList h fileName fileNameFull ;']);
setParent(rptgen_cml_eval9,rptgen_cfr_paragraph5);
 
% Create rptgen.cfr_text
rptgen_cfr_text5 = rptgen.cfr_text('isLiteral',true,'Content','');
setParent(rptgen_cfr_text5,rptgen_cfr_paragraph5);
 
% Create rptgen.cfr_section
rptgen_cfr_section6 = rptgen.cfr_section('SectionTitle','Expected Bounds Breaking Summary');
setParent(rptgen_cfr_section6,rptgen_cfr_section3);
 
% Create rptgen_lo.clo_for
rptgen_lo_clo_for1 = rptgen_lo.clo_for('EndNumber','6');
setParent(rptgen_lo_clo_for1,rptgen_cfr_section6);
 
% Create rptgen.cml_eval
rptgen_cml_eval10 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['switch RPTGEN_LOOP',sprintf('\n'),'  case 1',sprintf('\n'),'    plotCaption = ''General Metrics Projected Bounds Breaking'' ;',sprintf('\n'),'    plotFileName = ''gnrlProjBndsBreak'' ;',sprintf('\n'),'  case 2',sprintf('\n'),'    plotCaption = ''LDE Undershoot and 2DBlack Projected Bounds Breaking'' ;',sprintf('\n'),'    plotFileName = ''LDE2DBlkProjBndsBreak'' ;',sprintf('\n'),'  case 3',sprintf('\n'),'    plotCaption = ''Cosmic Ray Projected Bounds Breaking'' ;',sprintf('\n'),'    plotFileName = ''CRProjBndsBreak'' ;',sprintf('\n'),'  case 4',sprintf('\n'),'    plotCaption = ''CDPP 3-Hour Projected Bounds Breaking'' ;',sprintf('\n'),'    plotFileName = ''CDPP03ProjBndsBreak'' ;',sprintf('\n'),'  case 5',sprintf('\n'),'    plotCaption = ''CDPP 6-Hour Projected Bounds Breaking'' ;',sprintf('\n'),'    plotFileName = ''CDPP06ProjBndsBreak'' ;',sprintf('\n'),'  case 6',sprintf('\n'),'    plotCaption = ''CDPP 12-Hour Projected Bounds Breaking'' ;',sprintf('\n'),'    plotFileName = ''CDPP12ProjBndsBreak'' ;',sprintf('\n'),'end']);
setParent(rptgen_cml_eval10,rptgen_lo_clo_for1);
 
% Create rptgen.cml_eval
rptgen_cml_eval11 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['[axisLabels,adaptValues] = pmd_get_mjd_for_bounds_breaking( ...',sprintf('\n'),'   pmdOutputStruct.report,0,RPTGEN_LOOP) ;',sprintf('\n'),'[axisLabels,fixedValues] = pmd_get_mjd_for_bounds_breaking( ...',sprintf('\n'),'   pmdOutputStruct.report,1,RPTGEN_LOOP) ;',sprintf('\n'),'adaptTime = adaptValues - mjd2 ;',sprintf('\n'),'fixedTime = fixedValues - mjd2 ;',sprintf('\n'),'',sprintf('\n'),'figure ;',sprintf('\n'),'goodvals = find(adaptTime >= 0) ;',sprintf('\n'),'nGoodAdapt = length(goodvals) ;',sprintf('\n'),'plot(goodvals,adaptTime(goodvals),''bs'') ;',sprintf('\n'),'hold on',sprintf('\n'),'goodvals = find(fixedTime >= 0) ;',sprintf('\n'),'plot(goodvals,fixedTime(goodvals),''md'') ;',sprintf('\n'),'if (nGoodAdapt > 0)',sprintf('\n'),'  legend(''Adaptive Bounds'',''Fixed Bounds'') ;',sprintf('\n'),'else',sprintf('\n'),'  legend(''Fixed Bounds'') ;',sprintf('\n'),'end',sprintf('\n'),'axis([0 length(fixedTime)+1 0 pmdInputStruct.pmdModuleParameters.horizonTime+1]) ;',sprintf('\n'),'ylabel(''Time to Projected Bounds Break [days]'') ;',sprintf('\n'),'set(gca,''XTick'',1:length(fixedTime)) ;',sprintf('\n'),'set(gca,''XTickLabel'',axisLabels) ;',sprintf('\n'),'set(gcf,''Position'',[100 100 550 720]) ;',sprintf('\n'),'set(gca,''Position'',[0.13 0.16 0.775 0.815]) ;',sprintf('\n'),'rotate_x_tick_label(gca) ;',sprintf('\n'),'',sprintf('\n'),'fileName = pmd_get_plot_filename(plotFileName, ...',sprintf('\n'),'   ccdModule,ccdOutput,reportDateNum ) ;',sprintf('\n'),'saveas(gcf,fileName) ;',sprintf('\n'),'fileNameFull = fullfile(pwd,fileName) ;',sprintf('\n'),'fileNameFull = [fileNameFull,''.fig''] ;']);
setParent(rptgen_cml_eval11,rptgen_lo_clo_for1);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph6 = rptgen.cfr_paragraph;
setParent(rptgen_cfr_paragraph6,rptgen_lo_clo_for1);
 
% Create rptgen.cfr_link
rptgen_cfr_link3 = rptgen.cfr_link('LinkText','Open this Figure in Matlab',...
'LinkID','%<fileNameFull>',...
'LinkType','ulink');
setParent(rptgen_cfr_link3,rptgen_cfr_paragraph6);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap3 = rptgen_hg.chg_fig_snap('ImageFormat','jpeg90',...
'Caption','%<plotCaption>.  Missing values indicate missing metrics or metrics for which the projected out-of-bounds time exceeds the PMD trending time horizon.');
setParent(rptgen_hg_chg_fig_snap3,rptgen_cfr_paragraph6);
 
% Create rptgen.cml_eval
rptgen_cml_eval12 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['close all',sprintf('\n'),'clear fileName fileNameFull plotCaption plotFileName ;',sprintf('\n'),'clear axisLabels adaptValues fixedValues adaptTime fixedTime ;',sprintf('\n'),'clear goodvals ;']);
setParent(rptgen_cml_eval12,rptgen_cfr_paragraph6);
 
% Create rptgen.cfr_text
rptgen_cfr_text6 = rptgen.cfr_text('isLiteral',true,'Content','');
setParent(rptgen_cfr_text6,rptgen_cfr_paragraph6);
 
% Create rptgen.cfr_section
rptgen_cfr_section7 = rptgen.cfr_section('SectionTitle','Metric Tracking');
setParent(rptgen_cfr_section7,RptgenML_CReport1);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph7 = rptgen.cfr_paragraph;
setParent(rptgen_cfr_paragraph7,rptgen_cfr_section7);
 
% Create rptgen.cfr_text
rptgen_cfr_text7 = rptgen.cfr_text('isLiteral',true,'Content','');
setParent(rptgen_cfr_text7,rptgen_cfr_paragraph7);
 
% Create rptgen.cfr_section
rptgen_cfr_section8 = rptgen.cfr_section('SectionTitle','General Metrics');
setParent(rptgen_cfr_section8,rptgen_cfr_section7);
 
% Create rptgen.cml_eval
rptgen_cml_eval13 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['figure',sprintf('\n'),'inputTsData = pmdInputStruct.inputTsData ;',sprintf('\n'),'outputTsData = pmdOutputStruct.outputTsData ;',sprintf('\n'),'timestamps = pmdInputStruct.cadenceTimes.midTimestamps;',sprintf('\n'),'gapIndicators = pmdInputStruct.cadenceTimes.gapIndicators ;',sprintf('\n'),'parameters = pmdInputStruct.pmdModuleParameters ;',sprintf('\n'),'plotFileName = ''generalMetricTracking'' ;',sprintf('\n'),'fileName = pmd_get_plot_filename(plotFileName, ...',sprintf('\n'),'   ccdModule,ccdOutput,reportDateNum ) ;',sprintf('\n'),'fileNameFull = fullfile(pwd,fileName) ;',sprintf('\n'),'fileNameFull = [fileNameFull,''.fig''] ;']);
setParent(rptgen_cml_eval13,rptgen_cfr_section8);
 
% Create rptgen_lo.clo_for
rptgen_lo_clo_for2 = rptgen_lo.clo_for('EndNumber','11');
setParent(rptgen_lo_clo_for2,rptgen_cfr_section8);
 
% Create rptgen.cml_eval
rptgen_cml_eval14 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['metricName2 = '' '' ;',sprintf('\n'),'newTitle = char([]) ;',sprintf('\n'),'switch RPTGEN_LOOP',sprintf('\n'),'  case 1  % black level',sprintf('\n'),'    metricName = ''blackLevel'' ;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'  case 2  % smear level',sprintf('\n'),'    metricName = ''smearLevel'' ;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'  case 3  % dark current',sprintf('\n'),'    metricName = ''darkCurrent'' ;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'  case 4  % brightness',sprintf('\n'),'    metricName = ''brightness'' ;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'  case 5  % encircled energy',sprintf('\n'),'    metricName = ''encircledEnergy'' ;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'  case 6  % background level',sprintf('\n'),'    metricName = ''backgroundLevel'' ;',sprintf('\n'),'    tsData = outputTsData ;',sprintf('\n'),'    newTitle = ''bkgdLevel'' ;',sprintf('\n'),'  case 7  % centroids mean row',sprintf('\n'),'    metricName = ''centroidsMeanRow'' ;',sprintf('\n'),'    tsData = outputTsData ;',sprintf('\n'),'    newTitle = ''meanRow'' ;',sprintf('\n'),'  case 8  % centroids mean column',sprintf('\n'),'    metricName = ''centroidsMeanColumn'' ;',sprintf('\n'),'    newTitle = ''meanColumn'' ;',sprintf('\n'),'    tsData = outputTsData ;',sprintf('\n'),'  case 9  % plate scale metric',sprintf('\n'),'    metricName = ''plateScale'' ;',sprintf('\n'),'    tsData = outputTsData ;',sprintf('\n'),'  case 10 % compression theoretical efficiency',sprintf('\n'),'    metricName = ''theoreticalCompressionEfficiency'' ;',sprintf('\n'),'    metricName2 = ''compression'' ;',sprintf('\n'),'    newTitle = ''theoCompEff'' ;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'  case 11 % compression achieved efficiency',sprintf('\n'),'    metricName = ''achievedCompressionEfficiency'' ;',sprintf('\n'),'    newTitle = ''achvCompEff'' ;',sprintf('\n'),'    metricName2 = ''compression'' ;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'end',sprintf('\n'),'',sprintf('\n'),'subplot(4,3,RPTGEN_LOOP)',sprintf('\n'),'pmd_plot_time_series_metrics(tsData, pmdTempStruct, ...',sprintf('\n'),'   parameters, timestamps, gapIndicators, ...',sprintf('\n'),'   metricName, metricName2, 1, newTitle);',sprintf('\n'),'xlabel(char([])) ;']);
setParent(rptgen_cml_eval14,rptgen_lo_clo_for2);
 
% Create rptgen.cml_eval
rptgen_cml_eval15 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['set(gcf,''Position'',[100 100 700 750]) ;',sprintf('\n'),'saveas(gcf,fileName) ;']);
setParent(rptgen_cml_eval15,rptgen_cfr_section8);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph8 = rptgen.cfr_paragraph;
setParent(rptgen_cfr_paragraph8,rptgen_cfr_section8);
 
% Create rptgen.cfr_link
rptgen_cfr_link4 = rptgen.cfr_link('LinkText','Open This Figure in Matlab',...
'LinkID','%<fileNameFull>',...
'LinkType','ulink');
setParent(rptgen_cfr_link4,rptgen_cfr_paragraph8);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap4 = rptgen_hg.chg_fig_snap('ImageFormat','jpeg90',...
'Caption','Tracking of general metrics time series.  In all cases horizontal axis is days since first cadence.');
setParent(rptgen_hg_chg_fig_snap4,rptgen_cfr_section8);
 
% Create rptgen.cml_eval
rptgen_cml_eval16 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['clear fileName fileNameFull plotFileName metricName tsData ;',sprintf('\n'),'close(gcf) ;']);
setParent(rptgen_cml_eval16,rptgen_cfr_section8);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph9 = rptgen.cfr_paragraph;
setParent(rptgen_cfr_paragraph9,rptgen_cfr_section8);
 
% Create rptgen.cfr_text
rptgen_cfr_text8 = rptgen.cfr_text('isLiteral',true,'Content','');
setParent(rptgen_cfr_text8,rptgen_cfr_paragraph9);
 
% Create rptgen.cfr_section
rptgen_cfr_section9 = rptgen.cfr_section('SectionTitle',...
'LDE Undershoot and 2-D Black Metrics');
setParent(rptgen_cfr_section9,rptgen_cfr_section7);
 
% Create rptgen_lo.clo_for
rptgen_lo_clo_for3 = rptgen_lo.clo_for('EndNumber','7');
setParent(rptgen_lo_clo_for3,rptgen_cfr_section9);
 
% Create rptgen.cml_eval
rptgen_cml_eval17 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['metricName2 = '' '' ;',sprintf('\n'),'newTitle = char([]) ;',sprintf('\n'),'switch RPTGEN_LOOP',sprintf('\n'),'  case 1 % LDE Undershoot 1',sprintf('\n'),'    iType = 1;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'    metricName = ''ldeUndershoot'' ;',sprintf('\n'),'  case 2 % LDE undershoot 2',sprintf('\n'),'    iType = 2 ;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'    metricName = ''ldeUndershoot'' ;',sprintf('\n'),'  case 3 % LDE undershoot 3',sprintf('\n'),'    iType = 3 ;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'    metricName = ''ldeUndershoot''',sprintf('\n'),'  case 4 % 2-D black 1',sprintf('\n'),'    iType = 1 ;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'    metricName = ''twoDBlack'' ;',sprintf('\n'),'  case 5 % 2-D black 2',sprintf('\n'),'    iType = 2 ;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'    metricName = ''twoDBlack'' ;',sprintf('\n'),'  case 6 % 2-D black 3',sprintf('\n'),'    iType = 3 ;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'    metricName = ''twoDBlack'' ;',sprintf('\n'),'  case 7 % 2-D black 4',sprintf('\n'),'    iType = 4 ;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'    metricName = ''twoDBlack'' ;',sprintf('\n'),'end',sprintf('\n'),'',sprintf('\n'),'subplot(4,3,RPTGEN_LOOP)',sprintf('\n'),'pmd_plot_metrics_array(tsData, pmdTempStruct, parameters, ...',sprintf('\n'),'  timestamps, gapIndicators, iType, metricName ) ;',sprintf('\n'),'xlabel(char([])) ;',sprintf('\n'),'if (~isempty(deblank(newTitle)))',sprintf('\n'),'  title(newTitle) ;',sprintf('\n'),'end']);
setParent(rptgen_cml_eval17,rptgen_lo_clo_for3);
 
% Create rptgen.cml_eval
rptgen_cml_eval18 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['set(gcf,''Position'',[100 100 700 750]) ;',sprintf('\n'),'plotFileName = ''lde+2DBlackMetricTracking'' ;',sprintf('\n'),'fileName = pmd_get_plot_filename(plotFileName, ...',sprintf('\n'),'   ccdModule,ccdOutput,reportDateNum ) ;',sprintf('\n'),'fileNameFull = fullfile(pwd,fileName) ;',sprintf('\n'),'fileNameFull = [fileNameFull,''.fig''] ;',sprintf('\n'),'saveas(gcf,fileName) ;']);
setParent(rptgen_cml_eval18,rptgen_cfr_section9);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph10 = rptgen.cfr_paragraph;
setParent(rptgen_cfr_paragraph10,rptgen_cfr_section9);
 
% Create rptgen.cfr_link
rptgen_cfr_link5 = rptgen.cfr_link('LinkText','Open This Figure in Matlab',...
'LinkID','%<fileNameFull>',...
'LinkType','ulink');
setParent(rptgen_cfr_link5,rptgen_cfr_paragraph10);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap5 = rptgen_hg.chg_fig_snap('ImageFormat','jpeg90',...
'Caption','LDE Undershoot and 2-D Black metrics time series.  In all cases horizontal axis is days since first cadence.');
setParent(rptgen_hg_chg_fig_snap5,rptgen_cfr_section9);
 
% Create rptgen.cml_eval
rptgen_cml_eval19 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['close(gcf) ;',sprintf('\n'),'clear iType tsData metricType metricType2 ',sprintf('\n'),'clear newTitle fileName fileNameFull plotFileName']);
setParent(rptgen_cml_eval19,rptgen_cfr_section9);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph11 = rptgen.cfr_paragraph;
setParent(rptgen_cfr_paragraph11,rptgen_cfr_section9);
 
% Create rptgen.cfr_text
rptgen_cfr_text9 = rptgen.cfr_text('isLiteral',true,'Content','');
setParent(rptgen_cfr_text9,rptgen_cfr_paragraph11);
 
% Create rptgen.cfr_section
rptgen_cfr_section10 = rptgen.cfr_section('SectionTitle','Cosmic Ray Metrics');
setParent(rptgen_cfr_section10,rptgen_cfr_section7);
 
% Create rptgen_lo.clo_for
rptgen_lo_clo_for4 = rptgen_lo.clo_for('VariableName','metricArea');
setParent(rptgen_lo_clo_for4,rptgen_cfr_section10);
 
% Create rptgen_lo.clo_for
rptgen_lo_clo_for5 = rptgen_lo.clo_for('VariableName','metricType','EndNumber','3');
setParent(rptgen_lo_clo_for5,rptgen_lo_clo_for4);
 
% Create rptgen.cml_eval
rptgen_cml_eval20 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['plotNumber = metricType + (metricArea-1)*3 ;',sprintf('\n'),'',sprintf('\n'),'switch metricArea',sprintf('\n'),'  case 1',sprintf('\n'),'    metricName = ''black'' ;',sprintf('\n'),'  case 2',sprintf('\n'),'    metricName = ''maskedSmear'' ;',sprintf('\n'),'  case 3',sprintf('\n'),'    metricName = ''virtualSmear'' ;',sprintf('\n'),'  case 4',sprintf('\n'),'    metricName = ''targetStar'' ;',sprintf('\n'),'  case 5',sprintf('\n'),'    metricName = ''background'' ;',sprintf('\n'),'end',sprintf('\n'),'',sprintf('\n'),'switch metricType',sprintf('\n'),'  case 1',sprintf('\n'),'    metricName2 = ''hitRate'' ;',sprintf('\n'),'  case 2',sprintf('\n'),'    metricName2 = ''meanEnergy'' ;',sprintf('\n'),'  case 3',sprintf('\n'),'    metricName2 = ''energyVariance'' ;',sprintf('\n'),'end',sprintf('\n'),'',sprintf('\n'),'subplot(5,3,plotNumber) ;',sprintf('\n'),'pmd_plot_cosmic_ray_metrics(inputTsData, pmdTempStruct, ...',sprintf('\n'),'  parameters, timestamps, gapIndicators, ...',sprintf('\n'),'  metricName, metricName2) ;',sprintf('\n'),'xlabel(char([])) ;',sprintf('\n'),'title(char([])) ;']);
setParent(rptgen_cml_eval20,rptgen_lo_clo_for5);
 
% Create rptgen.cml_eval
rptgen_cml_eval21 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['set(gcf,''Position'',[100 100 700 800]) ;',sprintf('\n'),'',sprintf('\n'),'subplot(5,3,1)',sprintf('\n'),'title(''Hit Rate'') ;',sprintf('\n'),'subplot(5,3,2)',sprintf('\n'),'title(''Mean Energy'') ;',sprintf('\n'),'subplot(5,3,3)',sprintf('\n'),'title(''Energy Variance'') ;',sprintf('\n'),'',sprintf('\n'),'subplot(5,3,1)',sprintf('\n'),'ylabel(''black'');',sprintf('\n'),'subplot(5,3,4)',sprintf('\n'),'ylabel(''masked'')',sprintf('\n'),'subplot(5,3,7)',sprintf('\n'),'ylabel(''virtual'') ;',sprintf('\n'),'subplot(5,3,10) ;',sprintf('\n'),'ylabel(''target'') ;',sprintf('\n'),'subplot(5,3,13) ;',sprintf('\n'),'ylabel(''bkgd'') ;',sprintf('\n'),'',sprintf('\n'),'plotFileName = ''CRMetricTracking'' ;',sprintf('\n'),'fileName = pmd_get_plot_filename(plotFileName, ...',sprintf('\n'),'   ccdModule,ccdOutput,reportDateNum ) ;',sprintf('\n'),'fileNameFull = fullfile(pwd,fileName) ;',sprintf('\n'),'fileNameFull = [fileNameFull,''.fig''] ;',sprintf('\n'),'saveas(gcf,fileName) ;']);
setParent(rptgen_cml_eval21,rptgen_cfr_section10);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph12 = rptgen.cfr_paragraph;
setParent(rptgen_cfr_paragraph12,rptgen_cfr_section10);
 
% Create rptgen.cfr_link
rptgen_cfr_link6 = rptgen.cfr_link('LinkText','Open this Figure in Matlab',...
'LinkID','%<fileNameFull>',...
'LinkType','ulink');
setParent(rptgen_cfr_link6,rptgen_cfr_paragraph12);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap6 = rptgen_hg.chg_fig_snap('ImageFormat','jpeg90',...
'Caption','Cosmic ray metrics time series.   In all cases horizontal axis is days since first cadence.');
setParent(rptgen_hg_chg_fig_snap6,rptgen_cfr_section10);
 
% Create rptgen.cml_eval
rptgen_cml_eval22 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['close(gcf) ;',sprintf('\n'),'clear iType tsData metricType metricType2 plotNumber',sprintf('\n'),'clear newTitle fileName fileNameFull plotFileName']);
setParent(rptgen_cml_eval22,rptgen_cfr_section10);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph13 = rptgen.cfr_paragraph;
setParent(rptgen_cfr_paragraph13,rptgen_cfr_section10);
 
% Create rptgen.cfr_text
rptgen_cfr_text10 = rptgen.cfr_text('isLiteral',true,'Content','');
setParent(rptgen_cfr_text10,rptgen_cfr_paragraph13);
 
% Create rptgen.cfr_section
rptgen_cfr_section11 = rptgen.cfr_section('SectionTitle','CDPP Metrics');
setParent(rptgen_cfr_section11,rptgen_cfr_section7);
 
% Create rptgen_lo.clo_for
rptgen_lo_clo_for6 = rptgen_lo.clo_for('VariableName','iTime','EndNumber','3');
setParent(rptgen_lo_clo_for6,rptgen_cfr_section11);
 
% Create rptgen.cml_eval
rptgen_cml_eval23 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['switch iTime',sprintf('\n'),'  case 1',sprintf('\n'),'    timeString = ''threeHour'' ;',sprintf('\n'),'    sectionString = ''Three Hour Metrics'' ;',sprintf('\n'),'  case 2',sprintf('\n'),'    timeString = ''sixHour'' ;',sprintf('\n'),'    sectionString = ''Six Hour Metrics'' ;',sprintf('\n'),'  case 3',sprintf('\n'),'    timeString = ''twelveHour'' ;',sprintf('\n'),'    sectionString = ''Twelve Hour Metrics'' ;',sprintf('\n'),'end']);
setParent(rptgen_cml_eval23,rptgen_lo_clo_for6);
 
% Create rptgen.cfr_section
rptgen_cfr_section12 = rptgen.cfr_section('SectionTitle','%<sectionString>');
setParent(rptgen_cfr_section12,rptgen_lo_clo_for6);
 
% Create rptgen_lo.clo_for
rptgen_lo_clo_for7 = rptgen_lo.clo_for('VariableName','iFigNumber','EndNumber','2');
setParent(rptgen_lo_clo_for7,rptgen_cfr_section12);
 
% Create rptgen.cml_eval
rptgen_cml_eval24 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['if (iFigNumber == 1)',sprintf('\n'),'  nFigs = 9 ;',sprintf('\n'),'  nFigRows = 3 ;',sprintf('\n'),'  magString = {''mag9'',''mag10'',''mag11''} ;',sprintf('\n'),'  plotFileName = ''cdpp9to11Tracking'' ;',sprintf('\n'),'else',sprintf('\n'),'  nFigs = 12 ;',sprintf('\n'),'  nFigRows = 4 ;',sprintf('\n'),'  magString = {''mag12'',''mag13'',''mag14'',''mag15''} ;',sprintf('\n'),'  plotFileName = ''cdpp12to15Tracking'' ;',sprintf('\n'),'end',sprintf('\n'),'plotFileName =[plotFileName,''-'',timeString] ;']);
setParent(rptgen_cml_eval24,rptgen_lo_clo_for7);
 
% Create rptgen_lo.clo_for
rptgen_lo_clo_for8 = rptgen_lo.clo_for('VariableName','iFigRows','EndNumber','nFigRows');
setParent(rptgen_lo_clo_for8,rptgen_lo_clo_for7);
 
% Create rptgen_lo.clo_for
rptgen_lo_clo_for9 = rptgen_lo.clo_for('VariableName','iFigCols','EndNumber','3');
setParent(rptgen_lo_clo_for9,rptgen_lo_clo_for8);
 
% Create rptgen.cml_eval
rptgen_cml_eval25 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['figPointer = iFigCols + (iFigRows-1)*3 ;',sprintf('\n'),'switch iFigCols',sprintf('\n'),'  case 1',sprintf('\n'),'    plotType = ''cdppMeasured'' ;',sprintf('\n'),'  case 2',sprintf('\n'),'    plotType = ''cdppExpected'' ;',sprintf('\n'),'  case 3',sprintf('\n'),'    plotType = ''cdppRatio'' ;',sprintf('\n'),'end',sprintf('\n'),'',sprintf('\n'),'subplot(nFigRows,3,figPointer)',sprintf('\n'),'pmd_plot_cdpp_metrics( outputTsData, pmdTempStruct, ...',sprintf('\n'),'   parameters, timestamps, gapIndicators, plotType, ...',sprintf('\n'),'   magString{iFigRows}, timeString ) ;',sprintf('\n'),'xlabel(char([])) ;',sprintf('\n'),'title(char([])) ;']);
setParent(rptgen_cml_eval25,rptgen_lo_clo_for9);
 
% Create rptgen.cml_eval
rptgen_cml_eval26 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['if (iFigNumber == 1)',sprintf('\n'),'  set(gcf,''Position'',[100 100 700 750]) ;',sprintf('\n'),'else',sprintf('\n'),'  set(gcf,''Position'',[100 100 700 800]) ;',sprintf('\n'),'end',sprintf('\n'),'',sprintf('\n'),'subplot(nFigRows,3,1) ;',sprintf('\n'),'title(''Measured'') ;',sprintf('\n'),'subplot(nFigRows,3,2) ;',sprintf('\n'),'title(''Expected'') ;',sprintf('\n'),'subplot(nFigRows,3,3) ;',sprintf('\n'),'title(''Ratio'') ;',sprintf('\n'),'',sprintf('\n'),'subplot(nFigRows,3,1) ;',sprintf('\n'),'ylabel(magString{1}) ;',sprintf('\n'),'subplot(nFigRows,3,4) ;',sprintf('\n'),'ylabel(magString{2}) ;',sprintf('\n'),'subplot(nFigRows,3,7) ;',sprintf('\n'),'ylabel(magString{3}) ;',sprintf('\n'),'if (iFigNumber==2)',sprintf('\n'),'  subplot(nFigRows,3,10) ;',sprintf('\n'),'  ylabel(magString{4}) ;',sprintf('\n'),'end',sprintf('\n'),'fileName = pmd_get_plot_filename(plotFileName, ...',sprintf('\n'),'   ccdModule,ccdOutput,reportDateNum ) ;',sprintf('\n'),'fileNameFull = fullfile(pwd,fileName) ;',sprintf('\n'),'fileNameFull = [fileNameFull,''.fig''] ;',sprintf('\n'),'saveas(gcf,fileName) ;']);
setParent(rptgen_cml_eval26,rptgen_lo_clo_for7);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph14 = rptgen.cfr_paragraph;
setParent(rptgen_cfr_paragraph14,rptgen_lo_clo_for7);
 
% Create rptgen.cfr_link
rptgen_cfr_link7 = rptgen.cfr_link('LinkText','Open this File in Matlab',...
'LinkID','%<fileNameFull>',...
'LinkType','ulink');
setParent(rptgen_cfr_link7,rptgen_cfr_paragraph14);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap7 = rptgen_hg.chg_fig_snap('ImageFormat','jpeg90',...
'Caption','CDPP %<sectionString> Tracking, %<magString{1}> to %<magString{end}>.  In all cases horizontal axis is days since first cadence.');
setParent(rptgen_hg_chg_fig_snap7,rptgen_lo_clo_for7);
 
% Create rptgen.cml_eval
rptgen_cml_eval27 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString','close(gcf) ;');
setParent(rptgen_cml_eval27,rptgen_lo_clo_for7);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph15 = rptgen.cfr_paragraph;
setParent(rptgen_cfr_paragraph15,rptgen_lo_clo_for7);
 
% Create rptgen.cfr_text
rptgen_cfr_text11 = rptgen.cfr_text('isLiteral',true,'Content','');
setParent(rptgen_cfr_text11,rptgen_cfr_paragraph15);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph16 = rptgen.cfr_paragraph;
setParent(rptgen_cfr_paragraph16,rptgen_lo_clo_for6);
 
% Create rptgen.cfr_text
rptgen_cfr_text12 = rptgen.cfr_text('isLiteral',true,'Content','');
setParent(rptgen_cfr_text12,rptgen_cfr_paragraph16);
 
% Create rptgen.cfr_section
rptgen_cfr_section13 = rptgen.cfr_section('SectionTitle',...
'Tables of Bounds Breaking Information');
setParent(rptgen_cfr_section13,RptgenML_CReport1);
 
% Create rptgen.cfr_section
rptgen_cfr_section14 = rptgen.cfr_section('SectionTitle',...
'Table of Bounds-Breaking Events Summary');
setParent(rptgen_cfr_section14,rptgen_cfr_section13);
 
% Create rptgen.cml_eval
rptgen_cml_eval28 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['% [tab, sumTab] = pmd_get_table_of_anomalies( pmdOutputStruct.report, 10 ) ;',sprintf('\n'),'tab = [] ; ',sprintf('\n'),'sumTab = [] ;']);
setParent(rptgen_cml_eval28,rptgen_cfr_section14);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph17 = rptgen.cfr_paragraph('ParaText',...
'Summary Table disabled in report due to segfaults.  Grrr.');
setParent(rptgen_cfr_paragraph17,rptgen_cfr_section14);
 
% Create rptgen.cfr_section
rptgen_cfr_section15 = rptgen.cfr_section('SectionTitle','Table of Bounds Breaking Events');
setParent(rptgen_cfr_section15,rptgen_cfr_section13);
 
% Create rptgen.cml_eval
rptgen_cml_eval29 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString','clear tab sumTab ;');
setParent(rptgen_cml_eval29,rptgen_cfr_section15);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph18 = rptgen.cfr_paragraph('ParaText',...
'Anomaly Table disabled in report due to segfaults. Grrr.');
setParent(rptgen_cfr_paragraph18,rptgen_cfr_section15);
 
% Create rptgen.cfr_section
rptgen_cfr_section16 = rptgen.cfr_section('SectionTitle','Metric Trending');
setParent(rptgen_cfr_section16,RptgenML_CReport1);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph19 = rptgen.cfr_paragraph;
setParent(rptgen_cfr_paragraph19,rptgen_cfr_section16);
 
% Create rptgen.cfr_text
rptgen_cfr_text13 = rptgen.cfr_text('isLiteral',true,'Content','');
setParent(rptgen_cfr_text13,rptgen_cfr_paragraph19);
 
% Create rptgen.cfr_section
rptgen_cfr_section17 = rptgen.cfr_section('SectionTitle','General Metrics');
setParent(rptgen_cfr_section17,rptgen_cfr_section16);
 
% Create rptgen.cml_eval
rptgen_cml_eval30 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['plotFileName = ''generalMetricTrending'' ;',sprintf('\n'),'fileName = pmd_get_plot_filename(plotFileName, ...',sprintf('\n'),'   ccdModule,ccdOutput,reportDateNum ) ;',sprintf('\n'),'fileNameFull = fullfile(pwd,fileName) ;',sprintf('\n'),'fileNameFull = [fileNameFull,''.fig''] ;']);
setParent(rptgen_cml_eval30,rptgen_cfr_section17);
 
% Create rptgen_lo.clo_for
rptgen_lo_clo_for10 = rptgen_lo.clo_for('EndNumber','11');
setParent(rptgen_lo_clo_for10,rptgen_cfr_section17);
 
% Create rptgen.cml_eval
rptgen_cml_eval31 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['metricName2 = '' '' ;',sprintf('\n'),'newTitle = char([]) ;',sprintf('\n'),'switch RPTGEN_LOOP',sprintf('\n'),'  case 1  % black level',sprintf('\n'),'    metricName = ''blackLevel'' ;',sprintf('\n'),'    newTitle = metricName ;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'  case 2  % smear level',sprintf('\n'),'    metricName = ''smearLevel'' ;',sprintf('\n'),'    newTitle = metricName ;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'  case 3  % dark current',sprintf('\n'),'    metricName = ''darkCurrent'' ;',sprintf('\n'),'    newTitle = metricName ;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'  case 4  % brightness',sprintf('\n'),'    metricName = ''brightness'' ;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'  case 5  % encircled energy',sprintf('\n'),'    metricName = ''encircledEnergy'' ;',sprintf('\n'),'    newTitle = metricName ;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'  case 6  % background level',sprintf('\n'),'    metricName = ''backgroundLevel'' ;',sprintf('\n'),'    tsData = outputTsData ;',sprintf('\n'),'    newTitle = ''bkgdLevel'' ;',sprintf('\n'),'  case 7  % centroids mean row',sprintf('\n'),'    metricName = ''centroidsMeanRow'' ;',sprintf('\n'),'    tsData = outputTsData ;',sprintf('\n'),'    newTitle = ''meanRow'' ;',sprintf('\n'),'  case 8  % centroids mean column',sprintf('\n'),'    metricName = ''centroidsMeanColumn'' ;',sprintf('\n'),'    newTitle = ''meanColumn'' ;',sprintf('\n'),'    tsData = outputTsData ;',sprintf('\n'),'  case 9  % plate scale metric',sprintf('\n'),'    metricName = ''plateScale'' ;',sprintf('\n'),'    tsData = outputTsData ;',sprintf('\n'),'  case 10 % compression theoretical efficiency',sprintf('\n'),'    metricName = ''theoreticalCompressionEfficiency'' ;',sprintf('\n'),'    metricName2 = ''compression'' ;',sprintf('\n'),'    newTitle = ''theoCompEff'' ;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'  case 11 % compression achieved efficiency',sprintf('\n'),'    metricName = ''achievedCompressionEfficiency'' ;',sprintf('\n'),'    newTitle = ''achvCompEff'' ;',sprintf('\n'),'    metricName2 = ''compression'' ;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'end',sprintf('\n'),'',sprintf('\n'),'subplot(4,3,RPTGEN_LOOP)',sprintf('\n'),'if (isempty(newTitle))',sprintf('\n'),'  newTitle = metricName ;',sprintf('\n'),'end',sprintf('\n'),'[temp1,temp2] = pmd_track_trend_time_series_metrics( ...',sprintf('\n'),'   tsData, pmdOutputStruct, pmdTempStruct, parameters, ...',sprintf('\n'),'   timestamps, gapIndicators, ccdModule, ccdOutput, ...',sprintf('\n'),'   metricName, metricName2, newTitle ) ;',sprintf('\n'),'legend off',sprintf('\n'),'xlabel(char([])) ;',sprintf('\n'),'ylabel(char([])) ;']);
setParent(rptgen_cml_eval31,rptgen_lo_clo_for10);
 
% Create rptgen.cml_eval
rptgen_cml_eval32 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['set(gcf,''Position'',[100 100 700 750]) ;',sprintf('\n'),'saveas(gcf,fileName) ;']);
setParent(rptgen_cml_eval32,rptgen_cfr_section17);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph20 = rptgen.cfr_paragraph;
setParent(rptgen_cfr_paragraph20,rptgen_cfr_section17);
 
% Create rptgen.cfr_link
rptgen_cfr_link8 = rptgen.cfr_link('LinkText','Open this File with Matlab',...
'LinkID','%<fileNameFull>',...
'LinkType','ulink');
setParent(rptgen_cfr_link8,rptgen_cfr_paragraph20);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap8 = rptgen_hg.chg_fig_snap('ImageFormat','jpeg90',...
'Caption','Trending of general metrics time series.  In all cases horizontal axis is days since first cadence.');
setParent(rptgen_hg_chg_fig_snap8,rptgen_cfr_section17);
 
% Create rptgen.cml_eval
rptgen_cml_eval33 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['clear fileName fileNameFull plotFileName metricName tsData ;',sprintf('\n'),'close(gcf) ;']);
setParent(rptgen_cml_eval33,rptgen_cfr_section17);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph21 = rptgen.cfr_paragraph;
setParent(rptgen_cfr_paragraph21,rptgen_cfr_section17);
 
% Create rptgen.cfr_text
rptgen_cfr_text14 = rptgen.cfr_text('isLiteral',true,'Content','');
setParent(rptgen_cfr_text14,rptgen_cfr_paragraph21);
 
% Create rptgen.cfr_section
rptgen_cfr_section18 = rptgen.cfr_section('SectionTitle',...
'LDE Undershoot and 2-D Black Metrics');
setParent(rptgen_cfr_section18,rptgen_cfr_section16);
 
% Create rptgen_lo.clo_for
rptgen_lo_clo_for11 = rptgen_lo.clo_for('EndNumber','7');
setParent(rptgen_lo_clo_for11,rptgen_cfr_section18);
 
% Create rptgen.cml_eval
rptgen_cml_eval34 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['metricName2 = '' '' ;',sprintf('\n'),'newTitle = char([]) ;',sprintf('\n'),'switch RPTGEN_LOOP',sprintf('\n'),'  case 1 % LDE Undershoot 1',sprintf('\n'),'    iType = 1;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'    metricName = ''ldeUndershoot'' ;',sprintf('\n'),'    newTitle = ''ldeUndershoot1'' ;',sprintf('\n'),'  case 2 % LDE undershoot 2',sprintf('\n'),'    iType = 2 ;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'    metricName = ''ldeUndershoot'' ;',sprintf('\n'),'    newTitle = ''ldeUndershoot2'' ;',sprintf('\n'),'  case 3 % LDE undershoot 3',sprintf('\n'),'    iType = 3 ;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'    metricName = ''ldeUndershoot''',sprintf('\n'),'    newTitle = ''ldeUndershoot3'' ;',sprintf('\n'),'  case 4 % 2-D black 1',sprintf('\n'),'    iType = 1 ;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'    metricName = ''twoDBlack'' ;',sprintf('\n'),'    newTitle = ''2DBlack1'' ;',sprintf('\n'),'  case 5 % 2-D black 2',sprintf('\n'),'    iType = 2 ;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'    metricName = ''twoDBlack'' ;',sprintf('\n'),'    newTitle = ''2DBlack2'' ;',sprintf('\n'),'  case 6 % 2-D black 3',sprintf('\n'),'    iType = 3 ;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'    metricName = ''twoDBlack'' ;',sprintf('\n'),'    newTitle = ''2DBlack3'' ;',sprintf('\n'),'  case 7 % 2-D black 4',sprintf('\n'),'    iType = 4 ;',sprintf('\n'),'    tsData = inputTsData ;',sprintf('\n'),'    metricName = ''twoDBlack'' ;',sprintf('\n'),'    newTitle = ''2DBlack4'' ;',sprintf('\n'),'end',sprintf('\n'),'',sprintf('\n'),'subplot(4,3,RPTGEN_LOOP)',sprintf('\n'),'[temp1,temp2] = pmd_track_trend_metrics_array( ...',sprintf('\n'),'   tsData, pmdOutputStruct, pmdTempStruct, parameters, ...',sprintf('\n'),'   timestamps, gapIndicators, ccdModule, ccdOutput, ...',sprintf('\n'),'   iType, metricName, char([]), newTitle ) ;',sprintf('\n'),'legend off',sprintf('\n'),'xlabel(char([])) ;',sprintf('\n'),'ylabel(char([])) ;']);
setParent(rptgen_cml_eval34,rptgen_lo_clo_for11);
 
% Create rptgen.cml_eval
rptgen_cml_eval35 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['set(gcf,''Position'',[100 100 700 750]) ;',sprintf('\n'),'plotFileName = ''lde+2DBlackMetricTrending'' ;',sprintf('\n'),'fileName = pmd_get_plot_filename(plotFileName, ...',sprintf('\n'),'   ccdModule,ccdOutput,reportDateNum ) ;',sprintf('\n'),'fileNameFull = fullfile(pwd,fileName) ;',sprintf('\n'),'fileNameFull = [fileNameFull,''.fig''] ;',sprintf('\n'),'saveas(gcf,fileName) ;']);
setParent(rptgen_cml_eval35,rptgen_cfr_section18);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph22 = rptgen.cfr_paragraph;
setParent(rptgen_cfr_paragraph22,rptgen_cfr_section18);
 
% Create rptgen.cfr_link
rptgen_cfr_link9 = rptgen.cfr_link('LinkText','Open this Figure in Matlab',...
'LinkID','%<fileNameFull>',...
'LinkType','ulink');
setParent(rptgen_cfr_link9,rptgen_cfr_paragraph22);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap9 = rptgen_hg.chg_fig_snap('ImageFormat','jpeg90',...
'Caption','LDE Undershoot and 2-D Black metrics trends.  In all cases horizontal axis is days since first cadence.');
setParent(rptgen_hg_chg_fig_snap9,rptgen_cfr_section18);
 
% Create rptgen.cml_eval
rptgen_cml_eval36 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['close(gcf) ;',sprintf('\n'),'clear iType tsData metricType metricType2 ',sprintf('\n'),'clear newTitle fileName fileNameFull plotFileName']);
setParent(rptgen_cml_eval36,rptgen_cfr_section18);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph23 = rptgen.cfr_paragraph;
setParent(rptgen_cfr_paragraph23,rptgen_cfr_section18);
 
% Create rptgen.cfr_text
rptgen_cfr_text15 = rptgen.cfr_text('isLiteral',true,'Content','');
setParent(rptgen_cfr_text15,rptgen_cfr_paragraph23);
 
% Create rptgen.cfr_section
rptgen_cfr_section19 = rptgen.cfr_section('SectionTitle','Cosmic Ray Metrics');
setParent(rptgen_cfr_section19,rptgen_cfr_section16);
 
% Create rptgen_lo.clo_for
rptgen_lo_clo_for12 = rptgen_lo.clo_for('VariableName','metricArea');
setParent(rptgen_lo_clo_for12,rptgen_cfr_section19);
 
% Create rptgen_lo.clo_for
rptgen_lo_clo_for13 = rptgen_lo.clo_for('VariableName','metricType','EndNumber','3');
setParent(rptgen_lo_clo_for13,rptgen_lo_clo_for12);
 
% Create rptgen.cml_eval
rptgen_cml_eval37 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['plotNumber = metricType + (metricArea-1)*3 ;',sprintf('\n'),'',sprintf('\n'),'switch metricArea',sprintf('\n'),'  case 1',sprintf('\n'),'    metricName = ''black'' ;',sprintf('\n'),'  case 2',sprintf('\n'),'    metricName = ''maskedSmear'' ;',sprintf('\n'),'  case 3',sprintf('\n'),'    metricName = ''virtualSmear'' ;',sprintf('\n'),'  case 4',sprintf('\n'),'    metricName = ''targetStar'' ;',sprintf('\n'),'  case 5',sprintf('\n'),'    metricName = ''background'' ;',sprintf('\n'),'end',sprintf('\n'),'',sprintf('\n'),'switch metricType',sprintf('\n'),'  case 1',sprintf('\n'),'    metricName2 = ''hitRate'' ;',sprintf('\n'),'  case 2',sprintf('\n'),'    metricName2 = ''meanEnergy'' ;',sprintf('\n'),'  case 3',sprintf('\n'),'    metricName2 = ''energyVariance'' ;',sprintf('\n'),'end',sprintf('\n'),'',sprintf('\n'),'subplot(5,3,plotNumber) ;',sprintf('\n'),'[temp1, temp2] = pmd_track_trend_cosmic_ray_metrics(...',sprintf('\n'),'  inputTsData, pmdOutputStruct, pmdTempStruct, ...',sprintf('\n'),'  parameters, timestamps, gapIndicators, ...',sprintf('\n'),'  ccdModule, ccdOutput, metricName, metricName2, ''dmy'') ;',sprintf('\n'),'xlabel(char([])) ;',sprintf('\n'),'legend off ;',sprintf('\n'),'ylabel(char([])) ;',sprintf('\n'),'title(char([])) ;']);
setParent(rptgen_cml_eval37,rptgen_lo_clo_for13);
 
% Create rptgen.cml_eval
rptgen_cml_eval38 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['set(gcf,''Position'',[100 100 700 800]) ;',sprintf('\n'),'',sprintf('\n'),'subplot(5,3,1)',sprintf('\n'),'title(''Hit Rate'') ;',sprintf('\n'),'subplot(5,3,2)',sprintf('\n'),'title(''Mean Energy'') ;',sprintf('\n'),'subplot(5,3,3)',sprintf('\n'),'title(''Energy Variance'') ;',sprintf('\n'),'',sprintf('\n'),'subplot(5,3,1)',sprintf('\n'),'ylabel(''black'');',sprintf('\n'),'subplot(5,3,4)',sprintf('\n'),'ylabel(''masked'')',sprintf('\n'),'subplot(5,3,7)',sprintf('\n'),'ylabel(''virtual'') ;',sprintf('\n'),'subplot(5,3,10) ;',sprintf('\n'),'ylabel(''target'') ;',sprintf('\n'),'subplot(5,3,13) ;',sprintf('\n'),'ylabel(''bkgd'') ;',sprintf('\n'),'',sprintf('\n'),'plotFileName = ''CRMetricTrending'' ;',sprintf('\n'),'fileName = pmd_get_plot_filename(plotFileName, ...',sprintf('\n'),'   ccdModule,ccdOutput,reportDateNum ) ;',sprintf('\n'),'fileNameFull = fullfile(pwd,fileName) ;',sprintf('\n'),'fileNameFull = [fileNameFull,''.fig''] ;',sprintf('\n'),'saveas(gcf,fileName) ;']);
setParent(rptgen_cml_eval38,rptgen_cfr_section19);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph24 = rptgen.cfr_paragraph;
setParent(rptgen_cfr_paragraph24,rptgen_cfr_section19);
 
% Create rptgen.cfr_link
rptgen_cfr_link10 = rptgen.cfr_link('LinkText','Open this File in Matlab',...
'LinkID','%<fileNameFull>',...
'LinkType','ulink');
setParent(rptgen_cfr_link10,rptgen_cfr_paragraph24);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap10 = rptgen_hg.chg_fig_snap('ImageFormat','jpeg90',...
'Caption','Cosmic ray metrics time series trends.   In all cases horizontal axis is days since first cadence.');
setParent(rptgen_hg_chg_fig_snap10,rptgen_cfr_section19);
 
% Create rptgen.cml_eval
rptgen_cml_eval39 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['close(gcf) ;',sprintf('\n'),'clear iType tsData metricType metricType2 plotNumber',sprintf('\n'),'clear newTitle fileName fileNameFull plotFileName']);
setParent(rptgen_cml_eval39,rptgen_cfr_section19);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph25 = rptgen.cfr_paragraph;
setParent(rptgen_cfr_paragraph25,rptgen_cfr_section19);
 
% Create rptgen.cfr_text
rptgen_cfr_text16 = rptgen.cfr_text('isLiteral',true,'Content','');
setParent(rptgen_cfr_text16,rptgen_cfr_paragraph25);
 
% Create rptgen.cfr_section
rptgen_cfr_section20 = rptgen.cfr_section('SectionTitle','CDPP Metrics');
setParent(rptgen_cfr_section20,rptgen_cfr_section16);
 
% Create rptgen_lo.clo_for
rptgen_lo_clo_for14 = rptgen_lo.clo_for('VariableName','iTime','EndNumber','3');
setParent(rptgen_lo_clo_for14,rptgen_cfr_section20);
 
% Create rptgen.cml_eval
rptgen_cml_eval40 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['switch iTime',sprintf('\n'),'  case 1',sprintf('\n'),'    timeString = ''threeHour'' ;',sprintf('\n'),'    sectionString = ''Three Hour Metrics'' ;',sprintf('\n'),'  case 2',sprintf('\n'),'    timeString = ''sixHour'' ;',sprintf('\n'),'    sectionString = ''Six Hour Metrics'' ;',sprintf('\n'),'  case 3',sprintf('\n'),'    timeString = ''twelveHour'' ;',sprintf('\n'),'    sectionString = ''Twelve Hour Metrics'' ;',sprintf('\n'),'end']);
setParent(rptgen_cml_eval40,rptgen_lo_clo_for14);
 
% Create rptgen.cfr_section
rptgen_cfr_section21 = rptgen.cfr_section('SectionTitle','%<sectionString>');
setParent(rptgen_cfr_section21,rptgen_lo_clo_for14);
 
% Create rptgen_lo.clo_for
rptgen_lo_clo_for15 = rptgen_lo.clo_for('VariableName','iFigNumber','EndNumber','2');
setParent(rptgen_lo_clo_for15,rptgen_cfr_section21);
 
% Create rptgen.cml_eval
rptgen_cml_eval41 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['if (iFigNumber == 1)',sprintf('\n'),'  nFigs = 9 ;',sprintf('\n'),'  nFigRows = 3 ;',sprintf('\n'),'  magString = {''mag9'',''mag10'',''mag11''} ;',sprintf('\n'),'  plotFileName = ''cdpp9to11Trend'' ;',sprintf('\n'),'else',sprintf('\n'),'  nFigs = 12 ;',sprintf('\n'),'  nFigRows = 4 ;',sprintf('\n'),'  magString = {''mag12'',''mag13'',''mag14'',''mag15''} ;',sprintf('\n'),'  plotFileName = ''cdpp12to15Trend'' ;',sprintf('\n'),'end',sprintf('\n'),'plotFileName =[plotFileName,''-'',timeString] ;']);
setParent(rptgen_cml_eval41,rptgen_lo_clo_for15);
 
% Create rptgen_lo.clo_for
rptgen_lo_clo_for16 = rptgen_lo.clo_for('VariableName','iFigRows','EndNumber','nFigRows');
setParent(rptgen_lo_clo_for16,rptgen_lo_clo_for15);
 
% Create rptgen_lo.clo_for
rptgen_lo_clo_for17 = rptgen_lo.clo_for('VariableName','iFigCols','EndNumber','3');
setParent(rptgen_lo_clo_for17,rptgen_lo_clo_for16);
 
% Create rptgen.cml_eval
rptgen_cml_eval42 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['figPointer = iFigCols + (iFigRows-1)*3 ;',sprintf('\n'),'switch iFigCols',sprintf('\n'),'  case 1',sprintf('\n'),'    plotType = ''cdppMeasured'' ;',sprintf('\n'),'  case 2',sprintf('\n'),'    plotType = ''cdppExpected'' ;',sprintf('\n'),'  case 3',sprintf('\n'),'    plotType = ''cdppRatio'' ;',sprintf('\n'),'end',sprintf('\n'),'',sprintf('\n'),'subplot(nFigRows,3,figPointer)',sprintf('\n'),'[temp1, temp2] = pmd_track_trend_cdpp_metrics( outputTsData, ...',sprintf('\n'),'   pmdOutputStruct, pmdTempStruct, ...',sprintf('\n'),'   parameters, timestamps, gapIndicators, ccdModule,...',sprintf('\n'),'   ccdOutput, plotType, ...',sprintf('\n'),'   magString{iFigRows}, timeString, ''dummy'' ) ;',sprintf('\n'),'legend off ;',sprintf('\n'),'xlabel(char([])) ;',sprintf('\n'),'ylabel(char([])) ;',sprintf('\n'),'title(char([])) ;']);
setParent(rptgen_cml_eval42,rptgen_lo_clo_for17);
 
% Create rptgen.cml_eval
rptgen_cml_eval43 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['if (iFigNumber == 1)',sprintf('\n'),'  set(gcf,''Position'',[100 100 700 750]) ;',sprintf('\n'),'else',sprintf('\n'),'  set(gcf,''Position'',[100 100 700 800]) ;',sprintf('\n'),'end',sprintf('\n'),'',sprintf('\n'),'subplot(nFigRows,3,1) ;',sprintf('\n'),'title(''Measured'') ;',sprintf('\n'),'subplot(nFigRows,3,2) ;',sprintf('\n'),'title(''Expected'') ;',sprintf('\n'),'subplot(nFigRows,3,3) ;',sprintf('\n'),'title(''Ratio'') ;',sprintf('\n'),'',sprintf('\n'),'subplot(nFigRows,3,1) ;',sprintf('\n'),'ylabel(magString{1}) ;',sprintf('\n'),'subplot(nFigRows,3,4) ;',sprintf('\n'),'ylabel(magString{2}) ;',sprintf('\n'),'subplot(nFigRows,3,7) ;',sprintf('\n'),'ylabel(magString{3}) ;',sprintf('\n'),'if (iFigNumber==2)',sprintf('\n'),'  subplot(nFigRows,3,10) ;',sprintf('\n'),'  ylabel(magString{4}) ;',sprintf('\n'),'end',sprintf('\n'),'fileName = pmd_get_plot_filename(plotFileName, ...',sprintf('\n'),'   ccdModule,ccdOutput,reportDateNum ) ;',sprintf('\n'),'fileNameFull = fullfile(pwd,fileName) ;',sprintf('\n'),'fileNameFull = [fileNameFull,''.fig''] ;',sprintf('\n'),'saveas(gcf,fileName) ;']);
setParent(rptgen_cml_eval43,rptgen_lo_clo_for15);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph26 = rptgen.cfr_paragraph;
setParent(rptgen_cfr_paragraph26,rptgen_lo_clo_for15);
 
% Create rptgen.cfr_link
rptgen_cfr_link11 = rptgen.cfr_link('LinkText','Open this Figure in Matlab',...
'LinkID','%<fileNameFull>',...
'LinkType','ulink');
setParent(rptgen_cfr_link11,rptgen_cfr_paragraph26);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap11 = rptgen_hg.chg_fig_snap('ImageFormat','jpeg90',...
'Caption','CDPP %<sectionString> Trending, %<magString{1}> to %<magString{end}>.  In all cases horizontal axis is days since first cadence.');
setParent(rptgen_hg_chg_fig_snap11,rptgen_lo_clo_for15);
 
% Create rptgen.cml_eval
rptgen_cml_eval44 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString','close(gcf) ;');
setParent(rptgen_cml_eval44,rptgen_lo_clo_for15);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph27 = rptgen.cfr_paragraph;
setParent(rptgen_cfr_paragraph27,rptgen_lo_clo_for15);
 
% Create rptgen.cfr_text
rptgen_cfr_text17 = rptgen.cfr_text('isLiteral',true,'Content','');
setParent(rptgen_cfr_text17,rptgen_cfr_paragraph27);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph28 = rptgen.cfr_paragraph;
setParent(rptgen_cfr_paragraph28,rptgen_lo_clo_for14);
 
% Create rptgen.cfr_text
rptgen_cfr_text18 = rptgen.cfr_text('Content','');
setParent(rptgen_cfr_text18,rptgen_cfr_paragraph28);
 
