function [RptgenML_CReport1] = buildfpg
%BUILDFPG
% 
% Copyright 2017 United States Government as represented by the
% Administrator of the National Aeronautics and Space Administration.
% All Rights Reserved.
% 
% NASA acknowledges the SETI Institute's primary role in authoring and
% producing the Kepler Data Processing Pipeline under Cooperative
% Agreement Nos. NNA04CC63A, NNX07AD96A, NNX07AD98A, NNX11AI13A,
% NNX11AI14A, NNX13AD01A & NNX13AD16A.
% 
% This file is available under the terms of the NASA Open Source Agreement
% (NOSA). You should have received a copy of this agreement with the
% Kepler source code; see the file NASA-OPEN-SOURCE-AGREEMENT.doc.
% 
% No Warranty: THE SUBJECT SOFTWARE IS PROVIDED "AS IS" WITHOUT ANY
% WARRANTY OF ANY KIND, EITHER EXPRESSED, IMPLIED, OR STATUTORY,
% INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY THAT THE SUBJECT SOFTWARE
% WILL CONFORM TO SPECIFICATIONS, ANY IMPLIED WARRANTIES OF
% MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR FREEDOM FROM
% INFRINGEMENT, ANY WARRANTY THAT THE SUBJECT SOFTWARE WILL BE ERROR
% FREE, OR ANY WARRANTY THAT DOCUMENTATION, IF PROVIDED, WILL CONFORM
% TO THE SUBJECT SOFTWARE. THIS AGREEMENT DOES NOT, IN ANY MANNER,
% CONSTITUTE AN ENDORSEMENT BY GOVERNMENT AGENCY OR ANY PRIOR RECIPIENT
% OF ANY RESULTS, RESULTING DESIGNS, HARDWARE, SOFTWARE PRODUCTS OR ANY
% OTHER APPLICATIONS RESULTING FROM USE OF THE SUBJECT SOFTWARE.
% FURTHER, GOVERNMENT AGENCY DISCLAIMS ALL WARRANTIES AND LIABILITIES
% REGARDING THIRD-PARTY SOFTWARE, IF PRESENT IN THE ORIGINAL SOFTWARE,
% AND DISTRIBUTES IT "AS IS."
% 
% Waiver and Indemnity: RECIPIENT AGREES TO WAIVE ANY AND ALL CLAIMS
% AGAINST THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND
% SUBCONTRACTORS, AS WELL AS ANY PRIOR RECIPIENT. IF RECIPIENT'S USE OF
% THE SUBJECT SOFTWARE RESULTS IN ANY LIABILITIES, DEMANDS, DAMAGES,
% EXPENSES OR LOSSES ARISING FROM SUCH USE, INCLUDING ANY DAMAGES FROM
% PRODUCTS BASED ON, OR RESULTING FROM, RECIPIENT'S USE OF THE SUBJECT
% SOFTWARE, RECIPIENT SHALL INDEMNIFY AND HOLD HARMLESS THE UNITED
% STATES GOVERNMENT, ITS CONTRACTORS AND SUBCONTRACTORS, AS WELL AS ANY
% PRIOR RECIPIENT, TO THE EXTENT PERMITTED BY LAW. RECIPIENT'S SOLE
% REMEDY FOR ANY SUCH MATTER SHALL BE THE IMMEDIATE, UNILATERAL
% TERMINATION OF THIS AGREEMENT.
%
 
%  Auto-generated by MATLAB on 02-May-2009 21:38:52
 
% Create RptgenML.CReport
RptgenML_CReport1 = RptgenML.CReport('RptFileName',...
'c:\path\to\matlab\ct\fpg\mfiles\fpg.rpt',...
'Description','Report on the results of Focal Plane Geometry (FPG) fitting for the Kepler Mission.',...
'isAutoSaveOnGenerate',true,...
'Stylesheet','default-fo',...
'DirectoryType','pwd');
% setedit(RptgenML_CReport1);
 
% Create rptgen.cfr_titlepage
rptgen_cfr_titlepage1 = rptgen.cfr_titlepage('AuthorMode','none',...
'Title','Focal Plane Geometry Processing Report');
setParent(rptgen_cfr_titlepage1,RptgenML_CReport1);
 
% Create rptgen.cfr_section
rptgen_cfr_section1 = rptgen.cfr_section('SectionTitle','General Information');
setParent(rptgen_cfr_section1,RptgenML_CReport1);
 
% Create rptgen.cml_eval
rptgen_cml_eval1 = rptgen.cml_eval('isInsertString',false,...
'EvalString','disp([''generated:  '',local_time_to_utc(now,31)]) ;');
setParent(rptgen_cml_eval1,rptgen_cfr_section1);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph1 = rptgen.cfr_paragraph('ParaText','module:  fpg');
setParent(rptgen_cfr_paragraph1,rptgen_cfr_section1);
 
% Create rptgen.cfr_section
rptgen_cfr_section2 = rptgen.cfr_section('SectionTitle','Inputs');
setParent(rptgen_cfr_section2,RptgenML_CReport1);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph2 = rptgen.cfr_paragraph('ParaTitle','LC Mid-Time and Index #:',...
'TitleType','specify');
setParent(rptgen_cfr_paragraph2,rptgen_cfr_section2);
 
% Create rptgen.cml_eval
rptgen_cml_eval2 = rptgen.cml_eval('isInsertString',false,...
'EvalString',['v=sort(get(fpgResultsObject,''mjd'')); ',sprintf('\n'),'v=v(:) ; indx = 1:length(v) ; ',sprintf('\n'),'v = [v indx(:)] ;',sprintf('\n'),'disp(num2str(v,''%11.5f  %d\n''))']);
setParent(rptgen_cml_eval2,rptgen_cfr_paragraph2);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph3 = rptgen.cfr_paragraph('ParaTitle','Reference Cadence',...
'TitleType','specify');
setParent(rptgen_cfr_paragraph3,rptgen_cfr_section2);
 
% Create rptgen.cml_eval
rptgen_cml_eval3 = rptgen.cml_eval('isInsertString',false,...
'EvalString',['tAll = get(fpgResultsObject,''mjd'') ;',sprintf('\n'),'tRef = tAll(1) ;',sprintf('\n'),'tAllSort = sort(tAll) ;',sprintf('\n'),'indx = find(tAllSort == tRef) ;',sprintf('\n'),'disp([''MJD = '',num2str(tRef,''%11.5f''),''; LC # '',num2str(indx)]) ;']);
setParent(rptgen_cml_eval3,rptgen_cfr_paragraph3);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph4 = rptgen.cfr_paragraph('ParaTitle','Excluded Mod/Outs:',...
'TitleType','specify');
setParent(rptgen_cfr_paragraph4,rptgen_cfr_section2);
 
% Create rptgen.cml_eval
rptgen_cml_eval4 = rptgen.cml_eval('isInsertString',false,...
'EvalString',['m = get(fpgDataObject,''excludedModules'') ;',sprintf('\n'),'o = get(fpgDataObject,''excludedOutputs'') ;',sprintf('\n'),'disp(''Modules    Outputs'') ;',sprintf('\n'),'mo = [m(:) o(:)] ;',sprintf('\n'),'if (~isempty(mo))',sprintf('\n'),'disp(mo) ;',sprintf('\n'),'else',sprintf('\n'),'disp(''-------NONE-------'') ;',sprintf('\n'),'end']);
setParent(rptgen_cml_eval4,rptgen_cfr_paragraph4);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph5 = rptgen.cfr_paragraph('ParaTitle','Flags:','TitleType','specify');
setParent(rptgen_cfr_paragraph5,rptgen_cfr_section2);
 
% Create rptgen.cml_eval
rptgen_cml_eval5 = rptgen.cml_eval('isInsertString',false,...
'EvalString',['disp(''Flag   Value'')',sprintf('\n'),'disp([''tolX:                   '',num2str(get(fpgDataObject,''tolX''))]) ;',sprintf('\n'),'disp([''tolFun:                 '',num2str(get(fpgDataObject,''tolFun''))]) ;',sprintf('\n'),'disp([''tolSigma:               '',num2str(get(fpgDataObject,''tolSigma''))]) ;',sprintf('\n'),'disp([''fitPlateScaleFlag:      '',num2str(get(fpgDataObject,''fitPlateScaleFlag''))]) ;',sprintf('\n'),'disp([''fitPointingRefCadence:  '',num2str(get(fpgDataObject,''fitPointingRefCadence''))]) ;',sprintf('\n'),'disp([''doRobustFit:            '',num2str(get(fpgDataObject,''doRobustFit''))]) ;']);
setParent(rptgen_cml_eval5,rptgen_cfr_paragraph5);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph6 = rptgen.cfr_paragraph('ParaTitle','Grid Values:',...
'TitleType','specify');
setParent(rptgen_cfr_paragraph6,rptgen_cfr_section2);
 
% Create rptgen.cml_eval
rptgen_cml_eval6 = rptgen.cml_eval('isInsertString',false,...
'EvalString',['r=get(fpgDataObject,''rowGridValues'') ;',sprintf('\n'),'c=get(fpgDataObject,''columnGridValues'') ;',sprintf('\n'),'disp([''row:     '',num2str(r(:)'')]) ;',sprintf('\n'),'disp([''column:  '',num2str(c(:)'')]) ;']);
setParent(rptgen_cml_eval6,rptgen_cfr_paragraph6);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph7 = rptgen.cfr_paragraph('ParaTitle',...
'Input Spacecraft Pointing on Reference Cadence:','TitleType','specify');
setParent(rptgen_cfr_paragraph7,rptgen_cfr_section2);
 
% Create rptgen.cml_eval
rptgen_cml_eval7 = rptgen.cml_eval('isInsertString',false,...
'EvalString',['pointing=get(fpgResultsObject,''pointingRefCadence'') ;',sprintf('\n'),'disp([''RA:    '',num2str(pointing(1)),'' DEGREES'']) ;',sprintf('\n'),'disp([''Dec:   '',num2str(pointing(2)),'' degrees'']) ;',sprintf('\n'),'disp([''Roll:  '',num2str(pointing(3)),'' degrees'']) ;']);
setParent(rptgen_cml_eval7,rptgen_cfr_paragraph7);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph8 = rptgen.cfr_paragraph('ParaTitle','Spacecraft Pointing Source:',...
'TitleType','specify');
setParent(rptgen_cfr_paragraph8,rptgen_cfr_section2);
 
% Create rptgen.cml_eval
rptgen_cml_eval8 = rptgen.cml_eval('isInsertString',false,...
'EvalString',[' if (isfield(fpgDataStruct,''fpgModuleParameters''))',sprintf('\n'),'  if (fpgDataStruct.fpgModuleParameters.usePointingModel)',sprintf('\n'),'     pm = true ;',sprintf('\n'),'  else',sprintf('\n'),'     pm = false ;',sprintf('\n'),'  end ',sprintf('\n'),' else',sprintf('\n'),'  if (isfield(fpgDataStruct,''pointingRefCadence'') && ...',sprintf('\n'),'     ~isempty(fpgDataStruct.pointingRefCadence))',sprintf('\n'),'   pm = false ;',sprintf('\n'),'  else',sprintf('\n'),'   pm = true ;',sprintf('\n'),'  end',sprintf('\n'),' end',sprintf('\n'),'',sprintf('\n'),'if (pm)',sprintf('\n'),'disp(''pointing model'') ;',sprintf('\n'),'else',sprintf('\n'),'disp(''User-specified'') ;',sprintf('\n'),'end']);
setParent(rptgen_cml_eval8,rptgen_cfr_paragraph8);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph9 = rptgen.cfr_paragraph('ParaTitle','Spice Files:',...
'TitleType','specify');
setParent(rptgen_cfr_paragraph9,rptgen_cfr_section2);
 
% Create rptgen.cml_eval
rptgen_cml_eval9 = rptgen.cml_eval('isInsertString',false,...
'EvalString',['v=get(fpgDataObject,''raDec2PixModel'') ;',sprintf('\n'),'disp([''spacecraft ephemeris file:  '',v.spiceSpacecraftEphemerisFilename]) ;',sprintf('\n'),'disp([''planetary ephemeris file:   '',v.planetaryEphemerisFilename]) ;',sprintf('\n'),'disp([''leap second file:           '',v.leapSecondFilename]) ;']);
setParent(rptgen_cml_eval9,rptgen_cfr_paragraph9);
 
% Create rptgen.cfr_section
rptgen_cfr_section3 = rptgen.cfr_section('SectionTitle','Results');
setParent(rptgen_cfr_section3,RptgenML_CReport1);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph10 = rptgen.cfr_paragraph('ParaTitle',...
'Chi-square and # Degrees of Freedom','TitleType','specify');
setParent(rptgen_cfr_paragraph10,rptgen_cfr_section3);
 
% Create rptgen.cml_eval
rptgen_cml_eval10 = rptgen.cml_eval('isInsertString',false,...
'EvalString',['[c,n] = fpg_chisq(fpgResultsObject,0,0,0) ;',sprintf('\n'),'disp([''chisq = '',num2str(c),'', ndof = '',num2str(n),'', chisq/ndof = '',num2str(c/n)]) ;']);
setParent(rptgen_cml_eval10,rptgen_cfr_paragraph10);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph11 = rptgen.cfr_paragraph('ParaText',...
'All values are angles in DEGREES','ParaTitle','Focal Plane Geometry Parameters:',...
'TitleType','specify');
setParent(rptgen_cfr_paragraph11,rptgen_cfr_section3);
 
% Create rptgen.cml_eval
rptgen_cml_eval11 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['rd2po=get(fpgResultsObject,''raDec2PixObject'') ;',sprintf('\n'),'gm=get(rd2po,''geometryModel'') ;',sprintf('\n'),'p=gm.constants(1).array(1:126) ;',sprintf('\n'),'gmap=get(fpgResultsObject,''geometryParMap'') ;',sprintf('\n'),'gmapPtr=find(gmap~=0) ;',sprintf('\n'),'gmapNZ=gmap(gmapPtr) ;',sprintf('\n'),'ip=get(fpgResultsObject,''initialParValues'') ;',sprintf('\n'),'p0=p ; p0(gmapPtr)=ip(gmapNZ) ;',sprintf('\n'),'fp=get(fpgResultsObject,''finalParValues'') ;',sprintf('\n'),'p1=p ; p1(gmapPtr)=fp(gmapNZ) ;',sprintf('\n'),'dp=p1-p0 ;',sprintf('\n'),'sigp=zeros(size(p1)) ;',sprintf('\n'),'sig2=get(fpgResultsObject,''parValueCovariance'') ;',sprintf('\n'),'sig=sqrt(diag(sig2)) ; ',sprintf('\n'),'sigp(gmapPtr)=sig(gmapNZ) ;',sprintf('\n'),'[m,o]=convert_to_module_output(1:2:84) ;',sprintf('\n'),'m = [m(:)'' ; m(:)'' ; m(:)''] ;',sprintf('\n'),'o = [o(:)'' ; o(:)'' ; o(:)''] ;',sprintf('\n'),'m = m(:) ; o = o(:) ; op1 = o+1 ;',sprintf('\n'),'angle = [3 ; 2 ; 1] ;',sprintf('\n'),'angle = repmat(angle,42,1) ;',sprintf('\n'),'tab=num2cell([m angle p0(:) p1(:) dp(:) sigp(:)]) ;',sprintf('\n'),'header = {''mod/out'',''angle'',''initial'',''final'',''change'',''error''} ;',sprintf('\n'),'tab = [header ; tab] ;',sprintf('\n'),'for count = 2:size(tab,1)',sprintf('\n'),'tab{count,1} = [num2str(m(count-1)),''/'',num2str(o(count-1)),'','',num2str(op1(count-1))] ;',sprintf('\n'),'end']);
setParent(rptgen_cml_eval11,rptgen_cfr_paragraph11);
 
% Create rptgen.cfr_table
rptgen_cfr_table1 = rptgen.cfr_table('Source','tab');
setParent(rptgen_cfr_table1,rptgen_cfr_paragraph11);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph12 = rptgen.cfr_paragraph('ParaTitle','Plate Scale and Pincushion:',...
'TitleType','specify');
setParent(rptgen_cfr_paragraph12,rptgen_cfr_section3);
 
% Create rptgen_lo.clo_if
rptgen_lo_clo_if1 = rptgen_lo.clo_if('ConditionalString',...
'any(get(fpgResultsObject,''plateScaleParMap''))~=0');
setParent(rptgen_lo_clo_if1,rptgen_cfr_paragraph12);
 
% Create rptgen_lo.clo_then
rptgen_lo_clo_then1 = rptgen_lo.clo_then;
setParent(rptgen_lo_clo_then1,rptgen_lo_clo_if1);
 
% Create rptgen.cml_eval
rptgen_cml_eval12 = rptgen.cml_eval('isInsertString',false,...
'EvalString',['pmv=get(fpgResultsObject,''plateScaleParMap'') ;',sprintf('\n'),'ip=get(fpgResultsObject,''initialParValues'') ;',sprintf('\n'),'fp=get(fpgResultsObject,''finalParValues'') ;',sprintf('\n'),'sig=get(fpgResultsObject,''parValueCovariance'') ;',sprintf('\n'),'psf=get(fpgResultsObject,''pincushionScaleFactor'') ;',sprintf('\n'),'pm = find(pmv(:,1)~=0,1) ;',sprintf('\n'),'pm = pmv(pm,1) ;',sprintf('\n'),'if (pm ~= 0)',sprintf('\n'),'  disp(''PLATE SCALE:'') ;',sprintf('\n'),'  disp([''  Initial value:  '',num2str(ip(pm),''%8.6f''),'' arcsec/pixel'']) ;',sprintf('\n'),'  disp([''  Final value:    '',num2str(fp(pm),''%8.6f''),'' arcsec/pixel'']) ;',sprintf('\n'),'  disp([''  Change:         '',num2str(fp(pm)-ip(pm),''%e''),'' arcsec/pixel'']) ;',sprintf('\n'),'  disp([''  Error:          '',num2str(sqrt(sig(pm,pm)),''%e''),'' arcsec/pixel'']) ;',sprintf('\n'),'else',sprintf('\n'),'  disp(''Plate scale parameter not fitted.'') ;',sprintf('\n'),'end',sprintf('\n'),'pm = find(pmv(:,2)~=0,1) ;',sprintf('\n'),'pm = pmv(pm,2) ;',sprintf('\n'),'if (pm ~= 0)',sprintf('\n'),'  disp(''PINCUSHION:'') ;',sprintf('\n'),'  disp([''  Initial value:  '',num2str(ip(pm)/psf,''%e''),'' arcsec^-2'']) ;',sprintf('\n'),'  disp([''  Final value:    '',num2str(fp(pm)/psf,''%e''),'' arcsec^-2'']) ;',sprintf('\n'),'  disp([''  Change:         '',num2str((fp(pm)-ip(pm))/psf,''%e''),'' arcsec^-2'']) ;',sprintf('\n'),'  disp([''  Error:          '',num2str(sqrt(sig(pm,pm))/psf,''%e''),'' arcsec^-2'']) ;',sprintf('\n'),'else',sprintf('\n'),'  disp(''Pincushion parameter not fitted.'') ;',sprintf('\n'),'end']);
setParent(rptgen_cml_eval12,rptgen_lo_clo_then1);
 
% Create rptgen_lo.clo_else
rptgen_lo_clo_else1 = rptgen_lo.clo_else('TrueText','Plate scale parameter not fitted.');
setParent(rptgen_lo_clo_else1,rptgen_lo_clo_if1);
 
% Create rptgen.cfr_section
rptgen_cfr_section4 = rptgen.cfr_section('SectionTitle','Displays');
setParent(rptgen_cfr_section4,RptgenML_CReport1);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph13 = rptgen.cfr_paragraph;
setParent(rptgen_cfr_paragraph13,rptgen_cfr_section4);
 
% Create rptgen.cfr_text
rptgen_cfr_text1 = rptgen.cfr_text('isLiteral',true,...
'Content',['',sprintf('\n'),'',sprintf('\n'),'',sprintf('\n'),'',sprintf('\n'),'',sprintf('\n'),'',sprintf('\n'),'',sprintf('\n'),'',sprintf('\n'),'',sprintf('\n'),'',sprintf('\n'),'',sprintf('\n'),'',sprintf('\n'),'This page intentionally left blank.  See next page for start of displays!']);
setParent(rptgen_cfr_text1,rptgen_cfr_paragraph13);
 
% Create rptgen_lo.clo_if
rptgen_lo_clo_if2 = rptgen_lo.clo_if('ConditionalString',...
'~isempty(fpgResultsPlotHandles.Angle321)');
setParent(rptgen_lo_clo_if2,rptgen_cfr_section4);
 
% Create rptgen_lo.clo_then
rptgen_lo_clo_then2 = rptgen_lo.clo_then;
setParent(rptgen_lo_clo_then2,rptgen_lo_clo_if2);
 
% Create rptgen.cml_eval
rptgen_cml_eval13 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString','figure(fpgResultsPlotHandles.Angle321) ;');
setParent(rptgen_cml_eval13,rptgen_lo_clo_then2);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap1 = rptgen_hg.chg_fig_snap('ImageFormat','jpeg90',...
'ViewportSize',[5 7],...
'ViewportType','fixed',...
'Caption','Fitted Changes in 3-2-1 Angles');
setParent(rptgen_hg_chg_fig_snap1,rptgen_lo_clo_then2);
 
% Create rptgen_lo.clo_if
rptgen_lo_clo_if3 = rptgen_lo.clo_if('ConditionalString',...
'~isempty(fpgResultsPlotHandles.ccdMisalignments)');
setParent(rptgen_lo_clo_if3,rptgen_cfr_section4);
 
% Create rptgen_lo.clo_then
rptgen_lo_clo_then3 = rptgen_lo.clo_then;
setParent(rptgen_lo_clo_then3,rptgen_lo_clo_if3);
 
% Create rptgen.cml_eval
rptgen_cml_eval14 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString','figure(fpgResultsPlotHandles.ccdMisalignments) ;');
setParent(rptgen_cml_eval14,rptgen_lo_clo_then3);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap2 = rptgen_hg.chg_fig_snap('ImageFormat','jpeg90',...
'ViewportSize',[5 7],...
'ViewportType','fixed',...
'Caption','Fitted CCD Misalignments');
setParent(rptgen_hg_chg_fig_snap2,rptgen_lo_clo_then3);
 
% Create rptgen_lo.clo_if
rptgen_lo_clo_if4 = rptgen_lo.clo_if('ConditionalString',...
'~isempty(fpgResultsPlotHandles.pointingScatter)');
setParent(rptgen_lo_clo_if4,rptgen_cfr_section4);
 
% Create rptgen_lo.clo_then
rptgen_lo_clo_then4 = rptgen_lo.clo_then;
setParent(rptgen_lo_clo_then4,rptgen_lo_clo_if4);
 
% Create rptgen.cml_eval
rptgen_cml_eval15 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString','figure(fpgResultsPlotHandles.pointingScatter) ;');
setParent(rptgen_cml_eval15,rptgen_lo_clo_then4);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap3 = rptgen_hg.chg_fig_snap('ImageFormat','jpeg90','ViewportZoom',85,...
'ViewportSize',[5 7],...
'ViewportType','fixed',...
'Caption','Pointings on Cadences');
setParent(rptgen_hg_chg_fig_snap3,rptgen_lo_clo_then4);
 
% Create rptgen_lo.clo_if
rptgen_lo_clo_if5 = rptgen_lo.clo_if('ConditionalString',...
'~isempty(fpgResultsPlotHandles.pointingValue)');
setParent(rptgen_lo_clo_if5,rptgen_cfr_section4);
 
% Create rptgen_lo.clo_then
rptgen_lo_clo_then5 = rptgen_lo.clo_then;
setParent(rptgen_lo_clo_then5,rptgen_lo_clo_if5);
 
% Create rptgen.cml_eval
rptgen_cml_eval16 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString','figure(fpgResultsPlotHandles.pointingValue) ;');
setParent(rptgen_cml_eval16,rptgen_lo_clo_then5);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap4 = rptgen_hg.chg_fig_snap('ImageFormat','jpeg90','ViewportZoom',85,...
'ViewportSize',[5 7],...
'ViewportType','fixed',...
'Caption','Cadence Pointing Values');
setParent(rptgen_hg_chg_fig_snap4,rptgen_lo_clo_then5);
 
% Create rptgen_lo.clo_if
rptgen_lo_clo_if6 = rptgen_lo.clo_if('ConditionalString',...
'~isempty(fpgResultsPlotHandles.quiverBefore)');
setParent(rptgen_lo_clo_if6,rptgen_cfr_section4);
 
% Create rptgen_lo.clo_then
rptgen_lo_clo_then6 = rptgen_lo.clo_then;
setParent(rptgen_lo_clo_then6,rptgen_lo_clo_if6);
 
% Create rptgen.cml_eval
rptgen_cml_eval17 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString','figure(fpgResultsPlotHandles.quiverBefore) ;');
setParent(rptgen_cml_eval17,rptgen_lo_clo_then6);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap5 = rptgen_hg.chg_fig_snap('ImageFormat','jpeg90',...
'ViewportSize',[4.75 7],...
'ViewportType','fixed',...
'Caption','Constraint Point Quiver Plot -- Before Fitting.  Arrows point in the direction the CCD must move to accommodate the constraint point.');
setParent(rptgen_hg_chg_fig_snap5,rptgen_lo_clo_then6);
 
% Create rptgen_lo.clo_if
rptgen_lo_clo_if7 = rptgen_lo.clo_if('ConditionalString',...
'~isempty(fpgResultsPlotHandles.quiverAfter)');
setParent(rptgen_lo_clo_if7,rptgen_cfr_section4);
 
% Create rptgen_lo.clo_then
rptgen_lo_clo_then7 = rptgen_lo.clo_then;
setParent(rptgen_lo_clo_then7,rptgen_lo_clo_if7);
 
% Create rptgen.cml_eval
rptgen_cml_eval18 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString','figure(fpgResultsPlotHandles.quiverAfter) ;');
setParent(rptgen_cml_eval18,rptgen_lo_clo_then7);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap6 = rptgen_hg.chg_fig_snap('ImageFormat','jpeg90',...
'ViewportSize',[4.75 7],...
'ViewportType','fixed',...
'Caption','Constraint Point Quiver Plot -- After Fitting.  Arrows point in the direction the CCD must move to accommodate the constraint point.');
setParent(rptgen_hg_chg_fig_snap6,rptgen_lo_clo_then7);
 
% Create rptgen_lo.clo_if
rptgen_lo_clo_if8 = rptgen_lo.clo_if('ConditionalString',...
'~isempty(fpgResultsPlotHandles.residualsBefore)');
setParent(rptgen_lo_clo_if8,rptgen_cfr_section4);
 
% Create rptgen_lo.clo_then
rptgen_lo_clo_then8 = rptgen_lo.clo_then;
setParent(rptgen_lo_clo_then8,rptgen_lo_clo_if8);
 
% Create rptgen.cml_eval
rptgen_cml_eval19 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString','figure(fpgResultsPlotHandles.residualsBefore) ;');
setParent(rptgen_cml_eval19,rptgen_lo_clo_then8);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap7 = rptgen_hg.chg_fig_snap('ImageFormat','jpeg90',...
'ViewportSize',[5 7],...
'ViewportType','fixed',...
'Caption','Pre-Fitting Fit Residuals Distribution');
setParent(rptgen_hg_chg_fig_snap7,rptgen_lo_clo_then8);
 
% Create rptgen_lo.clo_if
rptgen_lo_clo_if9 = rptgen_lo.clo_if('ConditionalString',...
'~isempty(fpgResultsPlotHandles.residualsAfter)');
setParent(rptgen_lo_clo_if9,rptgen_cfr_section4);
 
% Create rptgen_lo.clo_then
rptgen_lo_clo_then9 = rptgen_lo.clo_then;
setParent(rptgen_lo_clo_then9,rptgen_lo_clo_if9);
 
% Create rptgen.cml_eval
rptgen_cml_eval20 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString','figure(fpgResultsPlotHandles.residualsAfter) ;');
setParent(rptgen_cml_eval20,rptgen_lo_clo_then9);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap8 = rptgen_hg.chg_fig_snap('ImageFormat','jpeg90',...
'ViewportSize',[5 7],...
'ViewportType','fixed',...
'Caption','Post-Fitting Fit Residuals Distribution');
setParent(rptgen_hg_chg_fig_snap8,rptgen_lo_clo_then9);
 
% Create rptgen_lo.clo_if
rptgen_lo_clo_if10 = rptgen_lo.clo_if('ConditionalString',...
'~isempty(fpgResultsPlotHandles.robustWeights)');
setParent(rptgen_lo_clo_if10,rptgen_cfr_section4);
 
% Create rptgen_lo.clo_then
rptgen_lo_clo_then10 = rptgen_lo.clo_then;
setParent(rptgen_lo_clo_then10,rptgen_lo_clo_if10);
 
% Create rptgen.cml_eval
rptgen_cml_eval21 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString','figure(fpgResultsPlotHandles.robustWeights) ;');
setParent(rptgen_cml_eval21,rptgen_lo_clo_then10);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap9 = rptgen_hg.chg_fig_snap('ImageFormat','jpeg90',...
'ViewportSize',[5 7],...
'ViewportType','fixed',...
'Caption','Weights Assigned by Robust Fitter');
setParent(rptgen_hg_chg_fig_snap9,rptgen_lo_clo_then10);
 
% Create rptgen_lo.clo_if
rptgen_lo_clo_if11 = rptgen_lo.clo_if('ConditionalString',...
'~isempty(fpgResultsPlotHandles.dataStatusMap)');
setParent(rptgen_lo_clo_if11,rptgen_cfr_section4);
 
% Create rptgen_lo.clo_then
rptgen_lo_clo_then11 = rptgen_lo.clo_then;
setParent(rptgen_lo_clo_then11,rptgen_lo_clo_if11);
 
% Create rptgen.cml_eval
rptgen_cml_eval22 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString','figure(fpgResultsPlotHandles.dataStatusMap) ;');
setParent(rptgen_cml_eval22,rptgen_lo_clo_then11);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap10 = rptgen_hg.chg_fig_snap('ImageFormat','jpeg90',...
'ViewportSize',[5 7],...
'ViewportType','fixed',...
'Caption','Data Status Map');
setParent(rptgen_hg_chg_fig_snap10,rptgen_lo_clo_then11);
 
% Create rptgen_lo.clo_if
rptgen_lo_clo_if12 = rptgen_lo.clo_if('ConditionalString','~isdeployed');
setParent(rptgen_lo_clo_if12,rptgen_cfr_section4);
 
% Create rptgen_lo.clo_then
rptgen_lo_clo_then12 = rptgen_lo.clo_then;
setParent(rptgen_lo_clo_then12,rptgen_lo_clo_if12);
 
% Create rptgen_lo.clo_if
rptgen_lo_clo_if13 = rptgen_lo.clo_if('ConditionalString',...
'~isempty(fpgResultsPlotHandles.correlationSurface)');
setParent(rptgen_lo_clo_if13,rptgen_lo_clo_then12);
 
% Create rptgen_lo.clo_then
rptgen_lo_clo_then13 = rptgen_lo.clo_then;
setParent(rptgen_lo_clo_then13,rptgen_lo_clo_if13);
 
% Create rptgen.cml_eval
rptgen_cml_eval23 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString','figure(fpgResultsPlotHandles.correlationSurface) ;');
setParent(rptgen_cml_eval23,rptgen_lo_clo_then13);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap11 = rptgen_hg.chg_fig_snap('ImageFormat','jpeg90',...
'ViewportSize',[5 7],...
'ViewportType','fixed',...
'Caption','Correlations in Covariance Matrix');
setParent(rptgen_hg_chg_fig_snap11,rptgen_lo_clo_then13);
 
% Create rptgen_lo.clo_if
rptgen_lo_clo_if14 = rptgen_lo.clo_if('ConditionalString',...
'~isempty(fpgResultsPlotHandles.correlationImage)');
setParent(rptgen_lo_clo_if14,rptgen_lo_clo_then12);
 
% Create rptgen_lo.clo_then
rptgen_lo_clo_then14 = rptgen_lo.clo_then;
setParent(rptgen_lo_clo_then14,rptgen_lo_clo_if14);
 
% Create rptgen.cml_eval
rptgen_cml_eval24 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString','figure(fpgResultsPlotHandles.correlationImage) ;');
setParent(rptgen_cml_eval24,rptgen_lo_clo_then14);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap12 = rptgen_hg.chg_fig_snap('ImageFormat','jpeg90',...
'ViewportSize',[5 7],...
'ViewportType','fixed',...
'Caption','Correlations in Covariance Matrix');
setParent(rptgen_hg_chg_fig_snap12,rptgen_lo_clo_then14);
 
% Create rptgen_lo.clo_if
rptgen_lo_clo_if15 = rptgen_lo.clo_if('ConditionalString',...
'~isempty(fpgResultsPlotHandles.globalCorrelation)');
setParent(rptgen_lo_clo_if15,rptgen_cfr_section4);
 
% Create rptgen_lo.clo_then
rptgen_lo_clo_then15 = rptgen_lo.clo_then;
setParent(rptgen_lo_clo_then15,rptgen_lo_clo_if15);
 
% Create rptgen.cml_eval
rptgen_cml_eval25 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString','figure(fpgResultsPlotHandles.globalCorrelation)');
setParent(rptgen_cml_eval25,rptgen_lo_clo_then15);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap13 = rptgen_hg.chg_fig_snap('ImageFormat','jpeg90',...
'ViewportSize',[5 7],...
'ViewportType','fixed',...
'Caption','FPG Fit Parameters Global Correlation');
setParent(rptgen_hg_chg_fig_snap13,rptgen_lo_clo_then15);
 
