function verify_sc_73pdc2_and_73pdc3(flightDataDirString)
%~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
% function verify_sc_73pdc3
%~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
%
% SOC73
%   The SOC shall be capable of processing short cadence and long cadence 
%   photometric data for any target.
%
% 73.PDC.2
%   PDC shall produce Corrected Flux time series at the same temporal 
%   resolution as the Relative Flux time series for both long and short cadences.
%
% 73.PDC.3
%   PDC shall be capable of producing corrected flux time series from relative 
%   flux time series generated by both aperture photometry (AP) and 
%   Difference Image Analysis (DIA)
%
%
% flightDataDirString
%
% ex. /path/to/flight/q2/i956/pdc-matlab-956-22686
%     /path/to/flight/q2/i956/pdc-matlab-956-22692
%     /path/to/flight/q2/i956/pdc-matlab-956-22703
%
%~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
% 
% Copyright 2017 United States Government as represented by the
% Administrator of the National Aeronautics and Space Administration.
% All Rights Reserved.
% 
% NASA acknowledges the SETI Institute's primary role in authoring and
% producing the Kepler Data Processing Pipeline under Cooperative
% Agreement Nos. NNA04CC63A, NNX07AD96A, NNX07AD98A, NNX11AI13A,
% NNX11AI14A, NNX13AD01A & NNX13AD16A.
% 
% This file is available under the terms of the NASA Open Source Agreement
% (NOSA). You should have received a copy of this agreement with the
% Kepler source code; see the file NASA-OPEN-SOURCE-AGREEMENT.doc.
% 
% No Warranty: THE SUBJECT SOFTWARE IS PROVIDED "AS IS" WITHOUT ANY
% WARRANTY OF ANY KIND, EITHER EXPRESSED, IMPLIED, OR STATUTORY,
% INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY THAT THE SUBJECT SOFTWARE
% WILL CONFORM TO SPECIFICATIONS, ANY IMPLIED WARRANTIES OF
% MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR FREEDOM FROM
% INFRINGEMENT, ANY WARRANTY THAT THE SUBJECT SOFTWARE WILL BE ERROR
% FREE, OR ANY WARRANTY THAT DOCUMENTATION, IF PROVIDED, WILL CONFORM
% TO THE SUBJECT SOFTWARE. THIS AGREEMENT DOES NOT, IN ANY MANNER,
% CONSTITUTE AN ENDORSEMENT BY GOVERNMENT AGENCY OR ANY PRIOR RECIPIENT
% OF ANY RESULTS, RESULTING DESIGNS, HARDWARE, SOFTWARE PRODUCTS OR ANY
% OTHER APPLICATIONS RESULTING FROM USE OF THE SUBJECT SOFTWARE.
% FURTHER, GOVERNMENT AGENCY DISCLAIMS ALL WARRANTIES AND LIABILITIES
% REGARDING THIRD-PARTY SOFTWARE, IF PRESENT IN THE ORIGINAL SOFTWARE,
% AND DISTRIBUTES IT "AS IS."
% 
% Waiver and Indemnity: RECIPIENT AGREES TO WAIVE ANY AND ALL CLAIMS
% AGAINST THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND
% SUBCONTRACTORS, AS WELL AS ANY PRIOR RECIPIENT. IF RECIPIENT'S USE OF
% THE SUBJECT SOFTWARE RESULTS IN ANY LIABILITIES, DEMANDS, DAMAGES,
% EXPENSES OR LOSSES ARISING FROM SUCH USE, INCLUDING ANY DAMAGES FROM
% PRODUCTS BASED ON, OR RESULTING FROM, RECIPIENT'S USE OF THE SUBJECT
% SOFTWARE, RECIPIENT SHALL INDEMNIFY AND HOLD HARMLESS THE UNITED
% STATES GOVERNMENT, ITS CONTRACTORS AND SUBCONTRACTORS, AS WELL AS ANY
% PRIOR RECIPIENT, TO THE EXTENT PERMITTED BY LAW. RECIPIENT'S SOLE
% REMEDY FOR ANY SUCH MATTER SHALL BE THE IMMEDIATE, UNILATERAL
% TERMINATION OF THIS AGREEMENT.
%


SCRATCHDIR = '/path/to/matlab/pdc/test/';
cd(SCRATCHDIR);

invocation = 0;
fileName = ['pdc-inputs-', num2str(invocation), '.mat'];

if nargin==1
    cd(flightDataDirString);
    load(fileName);
    cd(SCRATCHDIR);
else
    load(fileName);
end



display('#cadences in inputsStruct.cadenceTimes fields are: ')
display(['startTimestamps: ' num2str(length(inputsStruct.cadenceTimes.startTimestamps))])
display(' ')
display(['midTimestamps:   ' num2str(length(inputsStruct.cadenceTimes.midTimestamps))])
display(' ')
display(['endTimestamps:   ' num2str(length(inputsStruct.cadenceTimes.endTimestamps))])
display(' ')
display(['gapIndicators:   ' num2str(length(inputsStruct.cadenceTimes.gapIndicators))])
display(' ')
display(['cadenceNumbers:  ' num2str(length(inputsStruct.cadenceTimes.cadenceNumbers))])
display(' ')
display(' ')
display('#cadences in inputsStruct.targetDataStruct(i) fields are: ')
display(['values:        ' num2str(length(inputsStruct.targetDataStruct(1).values))])
display(' ')
display(['uncertainties: ' num2str(length(inputsStruct.targetDataStruct(1).uncertainties))])
display(' ')
display(['gapIndicators: ' num2str(length(inputsStruct.targetDataStruct(1).gapIndicators))])
display(' ')



pdcDataStruct = inputsStruct;
clear inputsStruct

mags = [pdcDataStruct.targetDataStruct.keplerMag];
rawFluxValues = [pdcDataStruct.targetDataStruct.values];
rawFluxUncertainties = [pdcDataStruct.targetDataStruct.uncertainties];
rawGapArray = [pdcDataStruct.targetDataStruct.gapIndicators];
clear pdcDataStruct



% create figures
printJpgFlag = false;
paperOrientationFlag = false;
includeTimeFlag      = false;

%---------------------------------------------------------
% figure 1
%---------------------------------------------------------
figure;
rawFluxValues(rawGapArray) = NaN;
plot(rawFluxValues);
title('[PDC] Raw Flux');
xlabel('Cadence');
ylabel('Flux (e-)');
%pause
fileNameStr = 'sc_req_73pdc3_figure1';
plot_to_file(fileNameStr, paperOrientationFlag, includeTimeFlag, printJpgFlag);


fileName = ['pdc-outputs-', num2str(invocation), '.mat'];
if nargin==1
    cd(flightDataDirString);
    load(fileName);
    cd(SCRATCHDIR);
else
    load(fileName);
end

pdcResultsStruct = outputsStruct;
clear outputsStruct

correctedFluxTimeSeries = ...
    [pdcResultsStruct.targetResultsStruct.correctedFluxTimeSeries];
correctedFluxValues = [correctedFluxTimeSeries.values];
correctedGapArray = [correctedFluxTimeSeries.gapIndicators];
clear pdcResultsStruct

%---------------------------------------------------------
% figure 2
%---------------------------------------------------------
figure;
correctedFluxValues(correctedGapArray) = NaN;
plot(correctedFluxValues);
title('[PDC] Corrected Flux');
xlabel('Cadence');
ylabel('Flux (e-)');
%pause
fileNameStr = 'sc_req_73pdc3_figure2';
plot_to_file(fileNameStr, paperOrientationFlag, includeTimeFlag, printJpgFlag);

nTargets = length(mags);
sigmaRawFlux = zeros([nTargets, 1]);
sigmaCorrectedFlux = zeros([nTargets, 1]);
rmsUncertainties = zeros([nTargets, 1]);
for iTarget = 1 : nTargets
    targetFlux = rawFluxValues( : , iTarget);
    targetUncertainties = rawFluxUncertainties( : , iTarget);
    targetGaps = rawGapArray( : , iTarget);
    sigmaRawFlux(iTarget) = std(targetFlux(~targetGaps));
    rmsUncertainties(iTarget) = ...
        sqrt(mean(targetUncertainties(~targetGaps) .^ 2));
    targetFlux = correctedFluxValues( : , iTarget);
    targetGaps = correctedGapArray( : , iTarget);
    sigmaCorrectedFlux(iTarget) = std(targetFlux(~targetGaps));
end

isValid = sum(~rawGapArray, 1)' > 1;
sigmaRawFlux(~isValid) = 0;
sigmaCorrectedFlux(~isValid) = 0;
rmsUncertainties(~isValid) = 0;

%---------------------------------------------------------
% figure 3
%---------------------------------------------------------
figure;
plot(mags(isValid), sigmaRawFlux(isValid) ./ rmsUncertainties(isValid), '.');
hold on
plot(mags(isValid), sigmaCorrectedFlux(isValid) ./ rmsUncertainties(isValid), '.r');
title('[PDC] Ratios of Flux Sigma to RMS Raw Flux Uncertainty vs Kepler Magnitude');
xlabel('Kepler Magnitude');
ylabel('Ratio');
legend('Raw Flux', 'Corrected Flux');
grid
%pause
fileNameStr = 'sc_req_73pdc3_figure3';
plot_to_file(fileNameStr, paperOrientationFlag, includeTimeFlag, printJpgFlag);

%hold off
%---------------------------------------------------------
% figure 4
%---------------------------------------------------------
figure;
loglog(sigmaRawFlux(isValid), sigmaCorrectedFlux(isValid), '.');
hold on
x = axis;
maxAxis = max(x);
minAxis = min(x);
loglog([minAxis; maxAxis], [minAxis; maxAxis], 'k');
hold off
title('[PDC] Raw and Corrected Flux Sigmas')
xlabel('Raw Flux Sigma (e-)');
ylabel('Corrected Flux Sigma (e-)');
grid
%pause
fileNameStr = 'sc_req_73pdc3_figure4';
plot_to_file(fileNameStr, paperOrientationFlag, includeTimeFlag, printJpgFlag);


return
