--
-- Copyright 2017 United States Government as represented by the
-- Administrator of the National Aeronautics and Space Administration.
-- All Rights Reserved.
-- 
-- This file is available under the terms of the NASA Open Source Agreement
-- (NOSA). You should have received a copy of this agreement with the
-- Kepler source code; see the file NASA-OPEN-SOURCE-AGREEMENT.doc.
-- 
-- No Warranty: THE SUBJECT SOFTWARE IS PROVIDED "AS IS" WITHOUT ANY
-- WARRANTY OF ANY KIND, EITHER EXPRESSED, IMPLIED, OR STATUTORY,
-- INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY THAT THE SUBJECT SOFTWARE
-- WILL CONFORM TO SPECIFICATIONS, ANY IMPLIED WARRANTIES OF
-- MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR FREEDOM FROM
-- INFRINGEMENT, ANY WARRANTY THAT THE SUBJECT SOFTWARE WILL BE ERROR
-- FREE, OR ANY WARRANTY THAT DOCUMENTATION, IF PROVIDED, WILL CONFORM
-- TO THE SUBJECT SOFTWARE. THIS AGREEMENT DOES NOT, IN ANY MANNER,
-- CONSTITUTE AN ENDORSEMENT BY GOVERNMENT AGENCY OR ANY PRIOR RECIPIENT
-- OF ANY RESULTS, RESULTING DESIGNS, HARDWARE, SOFTWARE PRODUCTS OR ANY
-- OTHER APPLICATIONS RESULTING FROM USE OF THE SUBJECT SOFTWARE.
-- FURTHER, GOVERNMENT AGENCY DISCLAIMS ALL WARRANTIES AND LIABILITIES
-- REGARDING THIRD-PARTY SOFTWARE, IF PRESENT IN THE ORIGINAL SOFTWARE,
-- AND DISTRIBUTES IT "AS IS."
--
-- Waiver and Indemnity: RECIPIENT AGREES TO WAIVE ANY AND ALL CLAIMS
-- AGAINST THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND
-- SUBCONTRACTORS, AS WELL AS ANY PRIOR RECIPIENT. IF RECIPIENT'S USE OF
-- THE SUBJECT SOFTWARE RESULTS IN ANY LIABILITIES, DEMANDS, DAMAGES,
-- EXPENSES OR LOSSES ARISING FROM SUCH USE, INCLUDING ANY DAMAGES FROM
-- PRODUCTS BASED ON, OR RESULTING FROM, RECIPIENT'S USE OF THE SUBJECT
-- SOFTWARE, RECIPIENT SHALL INDEMNIFY AND HOLD HARMLESS THE UNITED
-- STATES GOVERNMENT, ITS CONTRACTORS AND SUBCONTRACTORS, AS WELL AS ANY
-- PRIOR RECIPIENT, TO THE EXTENT PERMITTED BY LAW. RECIPIENT'S SOLE
-- REMEDY FOR ANY SUCH MATTER SHALL BE THE IMMEDIATE, UNILATERAL
-- TERMINATION OF THIS AGREEMENT.
--
CREATE TABLE JPOX_TABLES
(
    CLASS_NAME VARCHAR2(128) NOT NULL UNIQUE,
    "TABLE_NAME" VARCHAR2(128) NOT NULL,
    "TYPE" VARCHAR2(4) NOT NULL,
    OWNER VARCHAR2(2) NOT NULL,
    VERSION VARCHAR2(20) NOT NULL
);

CREATE TABLE CONFIG
(
    CONFIG_ID NUMBER NOT NULL,
    CREATED TIMESTAMP NULL,
    DESCRIPTION VARCHAR2(1000) NULL,
    "NAME" VARCHAR2(100) NULL,
    ROOT_NODE_CONFIGNODE_ID_VM NUMBER NULL
);

ALTER TABLE CONFIG ADD CONSTRAINT CONFIG_PK PRIMARY KEY (CONFIG_ID);

CREATE TABLE CONFIGNODE
(
    CONFIGNODE_ID NUMBER NOT NULL,
    CREATED TIMESTAMP NULL,
    MODULE_MODULE_ID_OID NUMBER NULL
);

ALTER TABLE CONFIGNODE ADD CONSTRAINT CONFIGNODE_PK PRIMARY KEY (CONFIGNODE_ID);

CREATE TABLE CONFIGNODE_NEXTNODES
(
    CONFIGNODE_ID_OID NUMBER NOT NULL,
    INTEGER_IDX NUMBER(10) NOT NULL,
    CONFIGNODE_ID_EID NUMBER NULL
);

ALTER TABLE CONFIGNODE_NEXTNODES ADD CONSTRAINT CONFIGNODE_NEXTNODES_PK PRIMARY KEY (CONFIGNODE_ID_OID,INTEGER_IDX);

CREATE TABLE "MODULE"
(
    MODULE_ID NUMBER NOT NULL,
    CREATED TIMESTAMP NULL,
    DESCRIPTION VARCHAR2(1000) NULL,
    "NAME" VARCHAR2(100) NULL,
    VERSION VARCHAR2(100) NULL
);

ALTER TABLE "MODULE" ADD CONSTRAINT MODULE_PK PRIMARY KEY (MODULE_ID);

ALTER TABLE CONFIG ADD CONSTRAINT CONFIG_FK1 FOREIGN KEY (ROOT_NODE_CONFIGNODE_ID_VM) REFERENCES CONFIGNODE (CONFIGNODE_ID) INITIALLY DEFERRED ;

CREATE INDEX CONFIG_N49 ON CONFIG (ROOT_NODE_CONFIGNODE_ID_VM);

ALTER TABLE CONFIGNODE ADD CONSTRAINT CONFIGNODE_FK1 FOREIGN KEY (MODULE_MODULE_ID_OID) REFERENCES "MODULE" (MODULE_ID) INITIALLY DEFERRED ;

CREATE INDEX CONFIGNODE_N49 ON CONFIGNODE (MODULE_MODULE_ID_OID);

ALTER TABLE CONFIGNODE_NEXTNODES ADD CONSTRAINT CONFIGNODE_NEXTNODES_FK1 FOREIGN KEY (CONFIGNODE_ID_OID) REFERENCES CONFIGNODE (CONFIGNODE_ID) INITIALLY DEFERRED ;

ALTER TABLE CONFIGNODE_NEXTNODES ADD CONSTRAINT CONFIGNODE_NEXTNODES_FK2 FOREIGN KEY (CONFIGNODE_ID_EID) REFERENCES CONFIGNODE (CONFIGNODE_ID) INITIALLY DEFERRED ;

CREATE INDEX CONFIGNODE_NEXTNODES_N49 ON CONFIGNODE_NEXTNODES (CONFIGNODE_ID_EID);

