function figure1 = plot_raDec2Pix_minus_MP(X1, Y1, Y2, Y3, Y4, quarterString, dimensionString)
%CREATEFIGURE(X1,Y1,Y2,Y3,Y4)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data
%  Y3:  vector of y data
%  Y4:  vector of y data
%  quarterString: e.g. 'Q8', to be appended to tile of plot (start)
%  dimensionString: e.g. 'ROW', to be appended to title of plot (end)
% 
% Copyright 2017 United States Government as represented by the
% Administrator of the National Aeronautics and Space Administration.
% All Rights Reserved.
% 
% NASA acknowledges the SETI Institute's primary role in authoring and
% producing the Kepler Data Processing Pipeline under Cooperative
% Agreement Nos. NNA04CC63A, NNX07AD96A, NNX07AD98A, NNX11AI13A,
% NNX11AI14A, NNX13AD01A & NNX13AD16A.
% 
% This file is available under the terms of the NASA Open Source Agreement
% (NOSA). You should have received a copy of this agreement with the
% Kepler source code; see the file NASA-OPEN-SOURCE-AGREEMENT.doc.
% 
% No Warranty: THE SUBJECT SOFTWARE IS PROVIDED "AS IS" WITHOUT ANY
% WARRANTY OF ANY KIND, EITHER EXPRESSED, IMPLIED, OR STATUTORY,
% INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY THAT THE SUBJECT SOFTWARE
% WILL CONFORM TO SPECIFICATIONS, ANY IMPLIED WARRANTIES OF
% MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR FREEDOM FROM
% INFRINGEMENT, ANY WARRANTY THAT THE SUBJECT SOFTWARE WILL BE ERROR
% FREE, OR ANY WARRANTY THAT DOCUMENTATION, IF PROVIDED, WILL CONFORM
% TO THE SUBJECT SOFTWARE. THIS AGREEMENT DOES NOT, IN ANY MANNER,
% CONSTITUTE AN ENDORSEMENT BY GOVERNMENT AGENCY OR ANY PRIOR RECIPIENT
% OF ANY RESULTS, RESULTING DESIGNS, HARDWARE, SOFTWARE PRODUCTS OR ANY
% OTHER APPLICATIONS RESULTING FROM USE OF THE SUBJECT SOFTWARE.
% FURTHER, GOVERNMENT AGENCY DISCLAIMS ALL WARRANTIES AND LIABILITIES
% REGARDING THIRD-PARTY SOFTWARE, IF PRESENT IN THE ORIGINAL SOFTWARE,
% AND DISTRIBUTES IT "AS IS."
% 
% Waiver and Indemnity: RECIPIENT AGREES TO WAIVE ANY AND ALL CLAIMS
% AGAINST THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND
% SUBCONTRACTORS, AS WELL AS ANY PRIOR RECIPIENT. IF RECIPIENT'S USE OF
% THE SUBJECT SOFTWARE RESULTS IN ANY LIABILITIES, DEMANDS, DAMAGES,
% EXPENSES OR LOSSES ARISING FROM SUCH USE, INCLUDING ANY DAMAGES FROM
% PRODUCTS BASED ON, OR RESULTING FROM, RECIPIENT'S USE OF THE SUBJECT
% SOFTWARE, RECIPIENT SHALL INDEMNIFY AND HOLD HARMLESS THE UNITED
% STATES GOVERNMENT, ITS CONTRACTORS AND SUBCONTRACTORS, AS WELL AS ANY
% PRIOR RECIPIENT, TO THE EXTENT PERMITTED BY LAW. RECIPIENT'S SOLE
% REMEDY FOR ANY SUCH MATTER SHALL BE THE IMMEDIATE, UNILATERAL
% TERMINATION OF THIS AGREEMENT.
%

%  Auto-generated by MATLAB on 13-Jun-2011 15:24:38

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'Position',[0.13 0.767258064516129 0.775 0.15660444545004]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 90]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 0.4]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'Marker','o','LineStyle','none');

% Create title
title(['\bf',quarterString,' MP Residuals (raDec2Pix - Motion Polynomial) - ',dimensionString]);

% Create ylabel
ylabel('\bfmax abs (pix)');

% Create axes
axes2 = axes('Parent',figure1,'Position',[0.13 0.548172043010753 0.775 0.15660444545004]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0 90]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[-0.1 0.1]);
box(axes2,'on');
grid(axes2,'on');
hold(axes2,'all');

% Create plot
plot(X1,Y2,'Parent',axes2,'Marker','o','LineStyle','none');

% Create ylabel
ylabel('\bffirst mode (pix)');

% Create axes
axes3 = axes('Parent',figure1,'Position',[0.13 0.329086021505376 0.775 0.15660444545004]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[0 90]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[0 0.06]);
box(axes3,'on');
grid(axes3,'on');
hold(axes3,'all');

% Create plot
plot(X1,Y3,'Parent',axes3,'Marker','o','LineStyle','none');

% Create ylabel
ylabel('\bfmad from first mode (pix)');

% Create axes
axes4 = axes('Parent',figure1,'Position',[0.13 0.11 0.775 0.15660444545004]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes4,[0 90]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes4,[0 0.25]);
box(axes4,'on');
grid(axes4,'on');
hold(axes4,'all');

% Create plot
plot(X1,Y4,'Parent',axes4,'Marker','o','LineStyle','none');

% Create ylabel
ylabel('\bfmax dev from first mode (pix)');

% Create xlabel
xlabel('\bfchannel #');

