function [sortedClassFrequ] = plotClassFrequency(csvFileName, topN)
%Processes CSV file generated by gov.nasa.kepler.fs.perf.StackTraceDumper
% 
% Copyright 2017 United States Government as represented by the
% Administrator of the National Aeronautics and Space Administration.
% All Rights Reserved.
% 
% This file is available under the terms of the NASA Open Source Agreement
% (NOSA). You should have received a copy of this agreement with the
% Kepler source code; see the file NASA-OPEN-SOURCE-AGREEMENT.doc.
% 
% No Warranty: THE SUBJECT SOFTWARE IS PROVIDED "AS IS" WITHOUT ANY
% WARRANTY OF ANY KIND, EITHER EXPRESSED, IMPLIED, OR STATUTORY,
% INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY THAT THE SUBJECT SOFTWARE
% WILL CONFORM TO SPECIFICATIONS, ANY IMPLIED WARRANTIES OF
% MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR FREEDOM FROM
% INFRINGEMENT, ANY WARRANTY THAT THE SUBJECT SOFTWARE WILL BE ERROR
% FREE, OR ANY WARRANTY THAT DOCUMENTATION, IF PROVIDED, WILL CONFORM
% TO THE SUBJECT SOFTWARE. THIS AGREEMENT DOES NOT, IN ANY MANNER,
% CONSTITUTE AN ENDORSEMENT BY GOVERNMENT AGENCY OR ANY PRIOR RECIPIENT
% OF ANY RESULTS, RESULTING DESIGNS, HARDWARE, SOFTWARE PRODUCTS OR ANY
% OTHER APPLICATIONS RESULTING FROM USE OF THE SUBJECT SOFTWARE.
% FURTHER, GOVERNMENT AGENCY DISCLAIMS ALL WARRANTIES AND LIABILITIES
% REGARDING THIRD-PARTY SOFTWARE, IF PRESENT IN THE ORIGINAL SOFTWARE,
% AND DISTRIBUTES IT "AS IS."
% 
% Waiver and Indemnity: RECIPIENT AGREES TO WAIVE ANY AND ALL CLAIMS
% AGAINST THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND
% SUBCONTRACTORS, AS WELL AS ANY PRIOR RECIPIENT. IF RECIPIENT'S USE OF
% THE SUBJECT SOFTWARE RESULTS IN ANY LIABILITIES, DEMANDS, DAMAGES,
% EXPENSES OR LOSSES ARISING FROM SUCH USE, INCLUDING ANY DAMAGES FROM
% PRODUCTS BASED ON, OR RESULTING FROM, RECIPIENT'S USE OF THE SUBJECT
% SOFTWARE, RECIPIENT SHALL INDEMNIFY AND HOLD HARMLESS THE UNITED
% STATES GOVERNMENT, ITS CONTRACTORS AND SUBCONTRACTORS, AS WELL AS ANY
% PRIOR RECIPIENT, TO THE EXTENT PERMITTED BY LAW. RECIPIENT'S SOLE
% REMEDY FOR ANY SUCH MATTER SHALL BE THE IMMEDIATE, UNILATERAL
% TERMINATION OF THIS AGREEMENT.
%

csvFile = fopen(csvFileName);
C = textscan(csvFile, '%u64%s%u%s%s', 'Delimiter', '|');
fclose(csvFile);

fullMethodNames = strcat(C{4}, C{5});
uniqueFullMethodNames = unique(fullMethodNames);

nDataPoints = length(uniqueFullMethodNames);
topN = min(topN, nDataPoints);
classFrequ = zeros(1, nDataPoints);
for i = 1:nDataPoints
    classFrequ(i)  = sum(ismember(fullMethodNames, uniqueFullMethodNames{i}));
end
classFrequ = log2(classFrequ)';


[sortedClassFrequ, sortedIndices] = sort(classFrequ, 1, 'descend');

for i = 1:nDataPoints
    uniqueFullMethodNamesByFrequ{i} = uniqueFullMethodNames{sortedIndices(i)};
end

sortedClassFrequ = flipud(sortedClassFrequ(1:topN));
uniqueFullMethodNamesByFrequ = fliplr({uniqueFullMethodNamesByFrequ{1:topN}});

%barh(1:length(uniqueClassNames), classFrequ)
barh(1:topN, sortedClassFrequ);
set(gca, 'YTickLabel', uniqueFullMethodNamesByFrequ);
set(gca, 'ytick', 1:topN);
hold on;
sortedClassFrequ(1:2:end) = NaN;
graphHandle = barh(1:topN, sortedClassFrequ);
set(graphHandle, 'FaceColor', [0.8 0.8 0.8]);
%get(graphHandle)
hold off;


