-- Put extra DDL statements here, like index creation.
-- This is run after all the Hibernate DDL statements.
-- Remember that Oracle has a 30 character limit on index, table and sequence
-- identifiers.
-- 
-- Copyright 2017 United States Government as represented by the
-- Administrator of the National Aeronautics and Space Administration.
-- All Rights Reserved.
-- 
-- This file is available under the terms of the NASA Open Source Agreement
-- (NOSA). You should have received a copy of this agreement with the
-- Kepler source code; see the file NASA-OPEN-SOURCE-AGREEMENT.doc.
-- 
-- No Warranty: THE SUBJECT SOFTWARE IS PROVIDED "AS IS" WITHOUT ANY
-- WARRANTY OF ANY KIND, EITHER EXPRESSED, IMPLIED, OR STATUTORY,
-- INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY THAT THE SUBJECT SOFTWARE
-- WILL CONFORM TO SPECIFICATIONS, ANY IMPLIED WARRANTIES OF
-- MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR FREEDOM FROM
-- INFRINGEMENT, ANY WARRANTY THAT THE SUBJECT SOFTWARE WILL BE ERROR
-- FREE, OR ANY WARRANTY THAT DOCUMENTATION, IF PROVIDED, WILL CONFORM
-- TO THE SUBJECT SOFTWARE. THIS AGREEMENT DOES NOT, IN ANY MANNER,
-- CONSTITUTE AN ENDORSEMENT BY GOVERNMENT AGENCY OR ANY PRIOR RECIPIENT
-- OF ANY RESULTS, RESULTING DESIGNS, HARDWARE, SOFTWARE PRODUCTS OR ANY
-- OTHER APPLICATIONS RESULTING FROM USE OF THE SUBJECT SOFTWARE.
-- FURTHER, GOVERNMENT AGENCY DISCLAIMS ALL WARRANTIES AND LIABILITIES
-- REGARDING THIRD-PARTY SOFTWARE, IF PRESENT IN THE ORIGINAL SOFTWARE,
-- AND DISTRIBUTES IT "AS IS."
--
-- Waiver and Indemnity: RECIPIENT AGREES TO WAIVE ANY AND ALL CLAIMS
-- AGAINST THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND
-- SUBCONTRACTORS, AS WELL AS ANY PRIOR RECIPIENT. IF RECIPIENT'S USE OF
-- THE SUBJECT SOFTWARE RESULTS IN ANY LIABILITIES, DEMANDS, DAMAGES,
-- EXPENSES OR LOSSES ARISING FROM SUCH USE, INCLUDING ANY DAMAGES FROM
-- PRODUCTS BASED ON, OR RESULTING FROM, RECIPIENT'S USE OF THE SUBJECT
-- SOFTWARE, RECIPIENT SHALL INDEMNIFY AND HOLD HARMLESS THE UNITED
-- STATES GOVERNMENT, ITS CONTRACTORS AND SUBCONTRACTORS, AS WELL AS ANY
-- PRIOR RECIPIENT, TO THE EXTENT PERMITTED BY LAW. RECIPIENT'S SOLE
-- REMEDY FOR ANY SUCH MATTER SHALL BE THE IMMEDIATE, UNILATERAL
-- TERMINATION OF THIS AGREEMENT.
-- 

-- TAD

create index TAD_OBSERVED_TARGET_L_IDX on TAD_OBSERVED_TARGET_LABELS(TAD_OBSERVED_TARGET_ID);
create index TAD_APERTURE_IDX on TAD_APERTURE(TAD_TARGET_TABLE_ID);
create index TAD_APERTURE_OFFSETS_IDX on TAD_APERTURE_OFFSETS(TAD_APERTURE_ID);
create index TAD_OBSERVED_TARGET_IDX on TAD_OBSERVED_TARGET(TAD_TARGET_TABLE_ID,CCD_MODULE,CCD_OUTPUT);
create index TAD_TARGET_DEFINITION_IDX on TAD_TARGET_DEFINITION(TAD_TARGET_TABLE_ID,CCD_MODULE,CCD_OUTPUT);
create index TAD_MASK_OFFSETS_IDX on TAD_MASK_OFFSETS(TAD_MASK_ID);
create index TAD_MASK_IDX on TAD_MASK(TAD_MASK_TABLE_ID);

-- PI

create unique index IDX_PI_PD_NV on PI_PIPELINE_DEF(PI_PD_NAME_NAME,VERSION);
create unique index IDX_PI_PS_NV on PI_PS(PI_PS_NAME_NAME,VERSION);
create unique index IDX_PI_MD_NV on PI_MOD_DEF(PI_MOD_NAME_NAME,VERSION);
create index PI_PT_PI_IDX on PI_PIPELINE_TASK (PI_PIPELINE_INSTANCE_ID);

-- DR

create index DR_PIXEL_LOG_CAD_IDX on DR_PIXEL_LOG(DATA_SET_TYPE,CADENCE_TYPE,CADENCE_NUMBER);

-- TPS

create index TPS_RESULT_ORIG_IDX on TPS_RESULT (PI_PIPELINE_TASK_ID);

