%~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
% Copy task files from NFS for PDQ testing
%~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
% 
% RLM, 4/8/2011
%~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
% 
% Copyright 2017 United States Government as represented by the
% Administrator of the National Aeronautics and Space Administration.
% All Rights Reserved.
% 
% NASA acknowledges the SETI Institute's primary role in authoring and
% producing the Kepler Data Processing Pipeline under Cooperative
% Agreement Nos. NNA04CC63A, NNX07AD96A, NNX07AD98A, NNX11AI13A,
% NNX11AI14A, NNX13AD01A & NNX13AD16A.
% 
% This file is available under the terms of the NASA Open Source Agreement
% (NOSA). You should have received a copy of this agreement with the
% Kepler source code; see the file NASA-OPEN-SOURCE-AGREEMENT.doc.
% 
% No Warranty: THE SUBJECT SOFTWARE IS PROVIDED "AS IS" WITHOUT ANY
% WARRANTY OF ANY KIND, EITHER EXPRESSED, IMPLIED, OR STATUTORY,
% INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY THAT THE SUBJECT SOFTWARE
% WILL CONFORM TO SPECIFICATIONS, ANY IMPLIED WARRANTIES OF
% MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR FREEDOM FROM
% INFRINGEMENT, ANY WARRANTY THAT THE SUBJECT SOFTWARE WILL BE ERROR
% FREE, OR ANY WARRANTY THAT DOCUMENTATION, IF PROVIDED, WILL CONFORM
% TO THE SUBJECT SOFTWARE. THIS AGREEMENT DOES NOT, IN ANY MANNER,
% CONSTITUTE AN ENDORSEMENT BY GOVERNMENT AGENCY OR ANY PRIOR RECIPIENT
% OF ANY RESULTS, RESULTING DESIGNS, HARDWARE, SOFTWARE PRODUCTS OR ANY
% OTHER APPLICATIONS RESULTING FROM USE OF THE SUBJECT SOFTWARE.
% FURTHER, GOVERNMENT AGENCY DISCLAIMS ALL WARRANTIES AND LIABILITIES
% REGARDING THIRD-PARTY SOFTWARE, IF PRESENT IN THE ORIGINAL SOFTWARE,
% AND DISTRIBUTES IT "AS IS."
% 
% Waiver and Indemnity: RECIPIENT AGREES TO WAIVE ANY AND ALL CLAIMS
% AGAINST THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND
% SUBCONTRACTORS, AS WELL AS ANY PRIOR RECIPIENT. IF RECIPIENT'S USE OF
% THE SUBJECT SOFTWARE RESULTS IN ANY LIABILITIES, DEMANDS, DAMAGES,
% EXPENSES OR LOSSES ARISING FROM SUCH USE, INCLUDING ANY DAMAGES FROM
% PRODUCTS BASED ON, OR RESULTING FROM, RECIPIENT'S USE OF THE SUBJECT
% SOFTWARE, RECIPIENT SHALL INDEMNIFY AND HOLD HARMLESS THE UNITED
% STATES GOVERNMENT, ITS CONTRACTORS AND SUBCONTRACTORS, AS WELL AS ANY
% PRIOR RECIPIENT, TO THE EXTENT PERMITTED BY LAW. RECIPIENT'S SOLE
% REMEDY FOR ANY SUCH MATTER SHALL BE THE IMMEDIATE, UNILATERAL
% TERMINATION OF THIS AGREEMENT.
%
programName       = 'pdq_copy_taskfiles_script'

%--------------------------------------------------------------------------
% List of contacts
%--------------------------------------------------------------------------
dataDirs = { ...
    '/path/to/q0/pipeline_results/ref_pixels/pdq-matlab-679-16455/',                                'q0/'; ...
    '/path/to/q0/pipeline_results/ref_pixels/r6.1_cdpp_pdq-matlab-1532-22705/',                     'q0/'; ...
    
    '/path/to/q1/pipeline_results/ref_pixels/pdq-matlab-116-7795/',                                 'q1/'; ...
    '/path/to/q1/pipeline_results/ref_pixels/pdq-matlab-678-16454/',                                'q1/'; ...
    '/path/to/q1/pipeline_results/ref_pixels/r6.1_q1_pdq-matlab-1535-22708/',                       'q1/'; ...
    
    '/path/to/q2/pipeline_results/ref_pixels/pdq-matlab-660-16436/',                                'q2/'; ...
    '/path/to/q2/pipeline_results/ref_pixels/r6.1_q2_pdq-matlab-1537-22710/',                       'q2/'; ...
    '/path/to/q2/pipeline_results/ref_pixels/keep--pdq-matlab-100-6480-8pixelsoff/' ,               'q2/'; ...
    
    '/path/to/q3/pipeline_results/ref_pixels/pdq-matlab-916-17369/',                                'q3/'; ...
    '/path/to/q3/pipeline_results/ref_pixels/pdq-matlab-917-17370/',                                'q3/'; ...
    '/path/to/q3/pipeline_results/ref_pixels/pdq-matlab-1538-22711-r6.1/',                          'q3/'; ...
    
    '/path/to/q4/pipeline_results/ref_pixels/pdq-matlab-1121-18614/',                               'q4/'; ...
    '/path/to/q4/pipeline_results/ref_pixels/pdq-matlab-1122-18615/',                               'q4/'; ...
    '/path/to/q4/pipeline_results/ref_pixels/pdq-matlab-1017-17470-r6.0/',                          'q4/'; ...
    '/path/to/q4/pipeline_results/ref_pixels/pdq-matlab-1539-22712-r6.1/',                          'q4/'; ...
    
    '/path/to/q5/pipeline_results/ref_pixels/kar-677/pdq-matlab-1522-22695/',                       'q5/'; ...
    '/path/to/q5/pipeline_results/ref_pixels/kar-677/q5_reproc_ksop799_pdq-matlab-3017-32513/',     'q5/'; ...
    '/path/to/q5/pipeline_results/ref_pixels/ksoc-855/pdq-matlab-1503-22676/',                      'q5/'; ... % data that triggered KSPC-855
    '/path/to/q5/pipeline_results/ref_pixels/pdq-matlab-1523-22696/',                               'q5/'; ...
    '/path/to/q5/pipeline_results/ref_pixels/pdq-matlab-1524-22697/',                               'q5/'; ...
    '/path/to/q5/pipeline_results/ref_pixels/pdq-matlab-1525-22698/',                               'q5/'; ...
    '/path/to/q5/pipeline_results/ref_pixels/r6.1_q5_pdq-matlab-2915-31671/',                       'q5/'; ...
        
    
    '/path/to/q6/pipeline_results/ref_pixels/pdq-matlab-1927-26020/',                               'q6/'; ...
    '/path/to/q6/pipeline_results/ref_pixels/pdq-matlab-1945-26038/',                               'q6/'; ...
    '/path/to/q6/pipeline_results/ref_pixels/pdq-matlab-1946-26039/',                               'q6/'; ...
    '/path/to/q6/pipeline_results/ref_pixels/pdq-matlab-1925-26018-ksoc718-merges/',                'q6/'; ...

    '/path/to/q7/pipeline_results/ref_pixels/pdq-matlab-1970-26046_keep/',                          'q7/'; ...
    '/path/to/q7/pipeline_results/ref_pixels/pdq-matlab-1988-26064_keep/',                          'q7/'; ...
    '/path/to/q7/pipeline_results/ref_pixels/pdq-matlab-1989-26065_reproc_all_q7/',                 'q7/'; ...
    '/path/to/q7/pipeline_results/ref_pixels/pdq-matlab-2214-27730/',                               'q7/'; ...
    '/path/to/q7/pipeline_results/ref_pixels/pdq-matlab-2274-27790/',                               'q7/'; ...
    '/path/to/q7/pipeline_results/ref_pixels/pdq-matlab-2275-27791/',                               'q7/'; ...
    '/path/to/q7/pipeline_results/ref_pixels/pdq-matlab-2276-27792/',                               'q7/'; ...
    
    '/path/to/q8/pipeline_results/ref_pixels/pdq-matlab-2775-31531/',                               'q8/'; ...
    '/path/to/q8/pipeline_results/ref_pixels/pdq-matlab-2795-31551/',                               'q8/'; ...
    '/path/to/q8/pipeline_results/ref_pixels/pdq-matlab-2815-31571/',                               'q8/'; ...
    '/path/to/q8/pipeline_results/ref_pixels/pdq-matlab-2835-31591/',                               'q8/'; ...
    '/path/to/q8/pipeline_results/ref_pixels/pdq-matlab-2855-31611/',                               'q8/'; ...
    '/path/to/q8/pipeline_results/ref_pixels/pdq-matlab-2875-31631/',                               'q8/'; ...
    '/path/to/q8/pipeline_results/ref_pixels/pdq-matlab-2895-31651/',                               'q8/'; ...
    '/path/to/q8/pipeline_results/ref_pixels/pdq-matlab-2916-31672/',                               'q8/'; ...
    
    '/path/to/q9/pipeline_results/ref_pixels/pdq-matlab-2957-31713/',                               'q9/'; ...
    '/path/to/q9/pipeline_results/ref_pixels/pdq-matlab-2996-32492/',                               'q9/'; ...
    '/path/to/q9/pipeline_results/ref_pixels/pdq-matlab-3016-32512/',                               'q9/'; ...
    '/path/to/q9/pipeline_results/ref_pixels/pdq-matlab-3036-32532/',                               'q9/'; ...

    
    % Quarterly Roll
    '/path/to/quarterly_rolls/march2011_quarterly_roll/pdq-matlab-2917-31673/',                     'quartertly_rolls/' ...

    }

toDirRoot           = '~/data/pdq_test_cases/ref_data_by_qtr'

%--------------------------------------------------------------------------
% Copy
%--------------------------------------------------------------------------
for n = 1:size(dataDirs,1)
    try
        fromDir = dataDirs{n,1};
        
        % Create new test directory
        while (fromDir(end) == '/')
            fromDir(end) = []; % strip trailing slashes
        end
        [dummy, subDir, ext] = fileparts(fromDir);
        
        % Handle directory names that contain a '.'. What a PAIN!
        if ~isempty(ext)
            subDir = strcat(subDir, ext);
        end
        
        toDir = fullfile(toDirRoot, dataDirs{n,2}, subDir);
        
        pdqval_copy_input_task_files(fromDir, toDir);
        
    catch
        errorThrown = lasterror;
        
        % Print stack trace to diary file
        stackLength = length(errorThrown.stack);
        for jStack = 1:stackLength
            disp(errorThrown.stack(jStack))
        end

        warning(programName,[errorThrown.message '   Unable to process ' dataDirs{n,1} ]);
        
    end
end
