/*
 * Copyright 2017 United States Government as represented by the
 * Administrator of the National Aeronautics and Space Administration.
 * All Rights Reserved.
 * 
 * This file is available under the terms of the NASA Open Source Agreement
 * (NOSA). You should have received a copy of this agreement with the
 * Kepler source code; see the file NASA-OPEN-SOURCE-AGREEMENT.doc.
 * 
 * No Warranty: THE SUBJECT SOFTWARE IS PROVIDED "AS IS" WITHOUT ANY
 * WARRANTY OF ANY KIND, EITHER EXPRESSED, IMPLIED, OR STATUTORY,
 * INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY THAT THE SUBJECT SOFTWARE
 * WILL CONFORM TO SPECIFICATIONS, ANY IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR FREEDOM FROM
 * INFRINGEMENT, ANY WARRANTY THAT THE SUBJECT SOFTWARE WILL BE ERROR
 * FREE, OR ANY WARRANTY THAT DOCUMENTATION, IF PROVIDED, WILL CONFORM
 * TO THE SUBJECT SOFTWARE. THIS AGREEMENT DOES NOT, IN ANY MANNER,
 * CONSTITUTE AN ENDORSEMENT BY GOVERNMENT AGENCY OR ANY PRIOR RECIPIENT
 * OF ANY RESULTS, RESULTING DESIGNS, HARDWARE, SOFTWARE PRODUCTS OR ANY
 * OTHER APPLICATIONS RESULTING FROM USE OF THE SUBJECT SOFTWARE.
 * FURTHER, GOVERNMENT AGENCY DISCLAIMS ALL WARRANTIES AND LIABILITIES
 * REGARDING THIRD-PARTY SOFTWARE, IF PRESENT IN THE ORIGINAL SOFTWARE,
 * AND DISTRIBUTES IT "AS IS."
 * 
 * Waiver and Indemnity: RECIPIENT AGREES TO WAIVE ANY AND ALL CLAIMS
 * AGAINST THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND
 * SUBCONTRACTORS, AS WELL AS ANY PRIOR RECIPIENT. IF RECIPIENT'S USE OF
 * THE SUBJECT SOFTWARE RESULTS IN ANY LIABILITIES, DEMANDS, DAMAGES,
 * EXPENSES OR LOSSES ARISING FROM SUCH USE, INCLUDING ANY DAMAGES FROM
 * PRODUCTS BASED ON, OR RESULTING FROM, RECIPIENT'S USE OF THE SUBJECT
 * SOFTWARE, RECIPIENT SHALL INDEMNIFY AND HOLD HARMLESS THE UNITED
 * STATES GOVERNMENT, ITS CONTRACTORS AND SUBCONTRACTORS, AS WELL AS ANY
 * PRIOR RECIPIENT, TO THE EXTENT PERMITTED BY LAW. RECIPIENT'S SOLE
 * REMEDY FOR ANY SUCH MATTER SHALL BE THE IMMEDIATE, UNILATERAL
 * TERMINATION OF THIS AGREEMENT.
 */

package gov.nasa.kepler.fs.client.util;

/**
 * An enumeration used to send a method id over the wire.  
 * 
 * This is used as a cheap way to define string constants.  The ordinal of these
 * is never used and so it is safe to change the ordering of these constants.
 * 
 * @author Sean McCauliff
 *
 */
public enum FileStoreMethods {
    WRITE_BLOB, READ_BLOB, BLOB_EXISTS, DELETE_BLOB,
    LOCAL_COMMIT, LOCAL_ROLLBACK, LOCAL_START,
    
    XA_COMMIT, XA_ROLLBACK, XA_START, XA_END, XA_FORGET, 
    XA_SET_TIMEOUT, XA_PREPARE, XA_RECOVER,
    
    INT_READ_TS,  INT_READ_ALL_TS,  
    FLOAT_READ_TS, FLOAT_READ_ALL_TS,
    READ_DOUBLE_TS, READ_DOUBLE_ALL_TS,
    READ_TS_BATCH,
    WRITE_TS, DELETE_TS,
    
    WRITE_CR, READ_CR, READ_ALL_CR, LIST_CR, DELETE_CR, READ_CR_BATCH,
    
    CLEAN,
    
    GET_INTERVALS, GET_IDS_FOR_SERIES, GET_SERVER_ID,
    
    SHUTDOWN,
    STATUS,
    PING,
    
    QUERY_FS_ID, QUERY_FS_IDS2, QUERY_FS_ID_PATH,
    CLOSE;
}
