% Compiles ETEM with the MATLAB compiler into a 'standalone' executable
% The executable still needs the ETEM directory structure
% (../so/Develop/ETEM2/...) and should be run in the ETEM directory
% 
% Copyright 2017 United States Government as represented by the
% Administrator of the National Aeronautics and Space Administration.
% All Rights Reserved.
% 
% This file is available under the terms of the NASA Open Source Agreement
% (NOSA). You should have received a copy of this agreement with the
% Kepler source code; see the file NASA-OPEN-SOURCE-AGREEMENT.doc.
% 
% No Warranty: THE SUBJECT SOFTWARE IS PROVIDED "AS IS" WITHOUT ANY
% WARRANTY OF ANY KIND, EITHER EXPRESSED, IMPLIED, OR STATUTORY,
% INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY THAT THE SUBJECT SOFTWARE
% WILL CONFORM TO SPECIFICATIONS, ANY IMPLIED WARRANTIES OF
% MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR FREEDOM FROM
% INFRINGEMENT, ANY WARRANTY THAT THE SUBJECT SOFTWARE WILL BE ERROR
% FREE, OR ANY WARRANTY THAT DOCUMENTATION, IF PROVIDED, WILL CONFORM
% TO THE SUBJECT SOFTWARE. THIS AGREEMENT DOES NOT, IN ANY MANNER,
% CONSTITUTE AN ENDORSEMENT BY GOVERNMENT AGENCY OR ANY PRIOR RECIPIENT
% OF ANY RESULTS, RESULTING DESIGNS, HARDWARE, SOFTWARE PRODUCTS OR ANY
% OTHER APPLICATIONS RESULTING FROM USE OF THE SUBJECT SOFTWARE.
% FURTHER, GOVERNMENT AGENCY DISCLAIMS ALL WARRANTIES AND LIABILITIES
% REGARDING THIRD-PARTY SOFTWARE, IF PRESENT IN THE ORIGINAL SOFTWARE,
% AND DISTRIBUTES IT "AS IS."
% 
% Waiver and Indemnity: RECIPIENT AGREES TO WAIVE ANY AND ALL CLAIMS
% AGAINST THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND
% SUBCONTRACTORS, AS WELL AS ANY PRIOR RECIPIENT. IF RECIPIENT'S USE OF
% THE SUBJECT SOFTWARE RESULTS IN ANY LIABILITIES, DEMANDS, DAMAGES,
% EXPENSES OR LOSSES ARISING FROM SUCH USE, INCLUDING ANY DAMAGES FROM
% PRODUCTS BASED ON, OR RESULTING FROM, RECIPIENT'S USE OF THE SUBJECT
% SOFTWARE, RECIPIENT SHALL INDEMNIFY AND HOLD HARMLESS THE UNITED
% STATES GOVERNMENT, ITS CONTRACTORS AND SUBCONTRACTORS, AS WELL AS ANY
% PRIOR RECIPIENT, TO THE EXTENT PERMITTED BY LAW. RECIPIENT'S SOLE
% REMEDY FOR ANY SUCH MATTER SHALL BE THE IMMEDIATE, UNILATERAL
% TERMINATION OF THIS AGREEMENT.
%

mcc -m ...
   etem2_wrapper.m ...
   etem2.m ...
   set_etem2_locations.m ...
   ETEM2_inputs_example.m ...
   defined_plugin_classes.m ...
   ./utilities/InverseOvercompleteWaveletTransform.m ...
   ./utilities/generate_vignetting_data.m ...
   ./utilities/mkppcdf.m ...
   ./utilities/bin_matrix.m ...
   ./utilities/compute_small_light_curve.m ...
   ./utilities/randp_tfu.m ...
   ./utilities/ETEM2_svn_version.m ...
   ./utilities/OvercompleteWaveletTransform.m ...
   ./utilities/calcnoisesig.m ...
   ./utilities/fake_zodi_model.m ...
   ./utilities/ppcdfinv.m ...
   ./utilities/evenextend.m ...
   ./utilities/make_binned_design_matrix.m ...
   ./utilities/daubh0.m ...
   ./utilities/select_structure_vectors.m ...
   ./utilities/gcrpdf.m ...
   ./utilities/make_tad_input.m ...
   ./utilities/consolidate_partitions.m ...
   ./utilities/scalerow.m ...
   ./utilities/zpad.m ...
   ./utilities/quick_centroid.m ...
   ./utilities/detrendcols.m ...
   ./utilities/compute_light_curve.m ...
   ./general_classes/@ccdClass/make_prf_poly.m ...
   ./general_classes/@ccdClass/project_stars.m ...
   ./general_classes/@ccdClass/make_motion_basis.m ...
   ./general_classes/@ccdClass/compute_ccd_poly.m ...
   ./general_classes/@ccdClass/ccdClass.m ...
   ./general_classes/@ccdClass/get_motion.m ...
   ./general_classes/@ccdClass/get.m ...
   ./general_classes/@ccdClass/draw_final_pixels.m ...
   ./general_classes/@ccdClass/make_ssr_pixel_bytes.m ...
   ./general_classes/@ccdClass/set_pixels_of_interest.m ...
   ./general_classes/@ccdClass/assign_stars.m ...
   ./general_classes/@ccdClass/render_time_series.m ...
   ./general_classes/@ccdClass/compute_visible_pixel_poly.m ...
   ./general_classes/@ccdClass/create_target_science_manager.m ...
   ./general_classes/@ccdClass/spill_saturation.m ...
   ./general_classes/@ccdClass/assign_targets.m ...
   ./general_classes/@ccdClass/identify_bad_fit_regions.m ...
   ./general_classes/@ccdClass/compute_polys.m ...
   ./general_classes/@ccdClass/make_intrapix_variability.m ...
   ./general_classes/@ccdClass/initialize_ccdPlanes.m ...
   ./general_classes/@ccdClass/render_ccd.m ...
   ./general_classes/@ccdClass/compute_ccd_effect_poly.m ...
   ./general_classes/@ccdClass/convert_electrons_to_ADU.m ...
   ./general_classes/@ccdClass/compute_target_poly.m ...
   ./general_classes/@ccdClass/write_tad_ssr_bytes.m ...
   ./general_classes/@runParamsClass/get.m ...
   ./general_classes/@runParamsClass/display.m ...
   ./general_classes/@runParamsClass/runParamsClass.m ...
   ./general_classes/@longCadenceDataClass/make_reference_pixels.m ...
   ./general_classes/@longCadenceDataClass/get.m ...
   ./general_classes/@longCadenceDataClass/make_ssr_pixel_bytes.m ...
   ./general_classes/@longCadenceDataClass/set_pixels_of_interest.m ...
   ./general_classes/@longCadenceDataClass/longCadenceDataClass.m ...
   ./general_classes/@ccdPlaneClass/save.m ...
   ./general_classes/@ccdPlaneClass/initialize.m ...
   ./general_classes/@ccdPlaneClass/compute_ccd_poly.m ...
   ./general_classes/@ccdPlaneClass/get.m ...
   ./general_classes/@ccdPlaneClass/write_ccd_poly_segment.m ...
   ./general_classes/@ccdPlaneClass/set_motion_design_matrix.m ...
   ./general_classes/@ccdPlaneClass/render_time_series.m ...
   ./general_classes/@ccdPlaneClass/compute_visible_pixel_poly.m ...
   ./general_classes/@ccdPlaneClass/ccdPlaneClass.m ...
   ./general_classes/@ccdPlaneClass/assign_targets.m ...
   ./general_classes/@ccdPlaneClass/select_stars.m ...
   ./general_classes/@ccdPlaneClass/compute_prf_poly.m ...
   ./general_classes/@ccdPlaneClass/construct_prf.m ...
   ./general_classes/@ccdPlaneClass/render_ccd.m ...
   ./general_classes/@ccdPlaneClass/compute_ccd_effect_poly.m ...
   ./general_classes/@ccdPlaneClass/compute_target_poly.m ...
   ./general_classes/@ccdPlaneClass/load.m ...
   ./general_classes/@ccdPlaneClass/read_ccd_poly_segment.m ...
   ./general_classes/@shortCadenceDataClass/make_reference_pixels.m ...
   ./general_classes/@shortCadenceDataClass/get.m ...
   ./general_classes/@shortCadenceDataClass/make_ssr_pixel_bytes.m ...
   ./general_classes/@shortCadenceDataClass/set_pixels_of_interest.m ...
   ./general_classes/@shortCadenceDataClass/shortCadenceDataClass.m ...
   ./general_classes/check_runParamsObject_inputs.m ...
   ./catalog_classes/@etem1CatalogReaderClass/assign_attributes.m ...
   ./catalog_classes/@etem1CatalogReaderClass/get.m ...
   ./catalog_classes/@etem1CatalogReaderClass/etem1CatalogReaderClass.m ...
   ./catalog_classes/@etem1CatalogReaderClass/read_catalog.m ...
   ./catalog_classes/@kicCatalogReaderClass/assign_attributes.m ...
   ./catalog_classes/@kicCatalogReaderClass/get.m ...
   ./catalog_classes/@kicCatalogReaderClass/read_catalog.m ...
   ./catalog_classes/@kicCatalogReaderClass/kicCatalogReaderClass.m ...
   ./motion_classes/@jitterMotionClass/jitterMotionClass.m ...
   ./motion_classes/@jitterMotionClass/get_motion.m ...
   ./motion_classes/@jitterMotionClass/get.m ...
   ./motion_classes/@jitterMotionClass/load_jitter_data.m ...
   ./motion_classes/@pointingJitterMotionClass/get_motion.m ...
   ./motion_classes/@pointingJitterMotionClass/get.m ...
   ./motion_classes/@pointingJitterMotionClass/load_jitter_data.m ...
   ./motion_classes/@pointingJitterMotionClass/pointingJitterMotionClass.m ...
   ./motion_classes/@jitterNoMotionClass/get_motion.m ...
   ./motion_classes/@jitterNoMotionClass/get.m ...
   ./motion_classes/@jitterNoMotionClass/jitterNoMotionClass.m ...
   ./motion_classes/@jitterNoMotionClass/load_jitter_data.m ...
   ./motion_classes/@dvaMotionClass/get_motion.m ...
   ./motion_classes/@dvaMotionClass/get.m ...
   ./motion_classes/@dvaMotionClass/dvaMotionClass.m ...
   ./motion_classes/@dvaNoMotionClass/get_motion.m ...
   ./motion_classes/@dvaNoMotionClass/get.m ...
   ./motion_classes/@dvaNoMotionClass/dvaNoMotionClass.m ...
   ./psf_classes/@specificPsfClass/specificPsfClass.m ...
   ./psf_classes/@specificPsfClass/get.m ...
   ./psf_classes/@specificPsfClass/get_psf.m ...
   ./star_selector_classes/@randomStarSelectorClass/select_stars.m ...
   ./star_selector_classes/@randomStarSelectorClass/randomStarSelectorClass.m ...
   ./additive_background_classes/@darkCurrentClass/get.m ...
   ./additive_background_classes/@darkCurrentClass/darkCurrentClass.m ...
   ./additive_background_classes/@stellarBackgroundClass/stellarBackgroundClass.m ...
   ./additive_background_classes/@stellarBackgroundClass/get.m ...
   ./additive_background_classes/@scalarZodiLightClass/get.m ...
   ./additive_background_classes/@scalarZodiLightClass/compute_zodiacal_light.m ...
   ./additive_background_classes/@scalarZodiLightClass/scalarZodiLightClass.m ...
   ./flat_field_component_classes/@vignettingClass/get.m ...
   ./flat_field_component_classes/@vignettingClass/vignettingClass.m ...
   ./flat_field_component_classes/@interPixelVariabilityClass/get.m ...
   ./flat_field_component_classes/@interPixelVariabilityClass/interPixelVariabilityClass.m ...
   ./radec2pix_classes/@noRaDec2PixClass/ra_dec_to_pix.m ...
   ./radec2pix_classes/@noRaDec2PixClass/unaberrate_pix_to_ra_dec.m ...
   ./radec2pix_classes/@noRaDec2PixClass/get.m ...
   ./radec2pix_classes/@noRaDec2PixClass/noRaDec2PixClass.m ...
   ./radec2pix_classes/@noRaDec2PixClass/pix_to_ra_dec.m ...
   ./radec2pix_classes/@oldRaDec2PixClass/ra_dec_to_pix.m ...
   ./radec2pix_classes/@oldRaDec2PixClass/unaberrate_pix_to_ra_dec.m ...
   ./radec2pix_classes/@oldRaDec2PixClass/get.m ...
   ./radec2pix_classes/@oldRaDec2PixClass/oldRaDec2PixClass.m ...
   ./radec2pix_classes/@oldRaDec2PixClass/pix_to_ra_dec.m ...
   ./radec2pix_classes/@productionRaDec2PixClass/ra_dec_to_pix.m ...
   ./radec2pix_classes/@productionRaDec2PixClass/unaberrate_pix_to_ra_dec.m ...
   ./radec2pix_classes/@productionRaDec2PixClass/get.m ...
   ./radec2pix_classes/@productionRaDec2PixClass/pix_to_ra_dec.m ...
   ./radec2pix_classes/@productionRaDec2PixClass/productionRaDec2PixClass.m ...
   ./target_selector_classes/@selectTargetByPropertyClass/select_targets.m ...
   ./target_selector_classes/@selectTargetByPropertyClass/selectTargetByPropertyClass.m ...
   ./pixel_effect_classes/@cteClass/cteClass.m ...
   ./pixel_effect_classes/@cteClass/apply_pixel_effect.m ...
   ./tad_input_classes/@runTadClass/runTadClass.m ...
   ./tad_input_classes/@runTadClass/get_tad_input.m ...
   ./tad_input_classes/@tadFileReaderClass/get_tad_input.m ...
   ./tad_input_classes/@tadFileReaderClass/tadFileReaderClass.m ...
   ./tad_input_classes/@databaseTadClass/databaseTadClass.m ...
   ./tad_input_classes/@databaseTadClass/get_tad_input.m ...
   ./pixel_noise_classes/@readNoiseClass/get.m ...
   ./pixel_noise_classes/@readNoiseClass/readNoiseClass.m ...
   ./pixel_noise_classes/@readNoiseClass/apply_noise.m ...
   ./pixel_noise_classes/@shotNoiseClass/apply_noise.m ...
   ./pixel_noise_classes/@shotNoiseClass/shotNoiseClass.m ...
   ./astrophysics_classes/stellar_properties_classes/@nonlinearLimbDarkeningClass/get_limb_darkening_coefficients.m ...
   ./astrophysics_classes/stellar_properties_classes/@nonlinearLimbDarkeningClass/nonlinearLimbDarkeningClass.m ...
   ./astrophysics_classes/stellar_properties_classes/@simpleStellarPropertiesClass/simpleStellarPropertiesClass.m ...
   ./astrophysics_classes/stellar_properties_classes/@simpleStellarPropertiesClass/get_stellar_properties.m ...
   ./astrophysics_classes/stellar_properties_classes/@simpleStellarPropertiesClass/get_spectral_type_mass_radius.m ...
   ./astrophysics_classes/@cosmicRayClass/cosmicRayClass.m ...
   ./astrophysics_classes/@cosmicRayClass/add_cosmic_rays.m ...
   ./astrophysics_classes/@targetScienceManagerClass/targetScienceManagerClass.m ...
   ./astrophysics_classes/@targetScienceManagerClass/get.m ...
   ./astrophysics_classes/lightcurve_classes/@transitingSystemClass/limb_darkening.m ...
   ./astrophysics_classes/lightcurve_classes/@transitingSystemClass/transitingSystemClass.m ...
   ./astrophysics_classes/lightcurve_classes/@sohoSolarVariabilityClass/generate_stellar_variability_curves.m ...
   ./astrophysics_classes/lightcurve_classes/@sohoSolarVariabilityClass/get.m ...
   ./astrophysics_classes/lightcurve_classes/@sohoSolarVariabilityClass/sohoSolarVariabilityClass.m ...
   ./astrophysics_classes/lightcurve_classes/@sohoSolarVariabilityClass/create_light_curve.m ...
   ./astrophysics_classes/lightcurve_classes/@testSineClass/create_light_curve.m ...
   ./astrophysics_classes/lightcurve_classes/@testSineClass/testSineClass.m ...
   ./astrophysics_classes/lightcurve_classes/@transitingOrbitClass/large_transit_light_curve.m ...
   ./astrophysics_classes/lightcurve_classes/@transitingOrbitClass/compute_transit_orbit.m ...
   ./astrophysics_classes/lightcurve_classes/@transitingOrbitClass/create_light_curve.m ...
   ./astrophysics_classes/lightcurve_classes/@transitingOrbitClass/compute_kepler_orbit.m ...
   ./astrophysics_classes/lightcurve_classes/@transitingOrbitClass/transitingOrbitClass.m ...
   ./astrophysics_classes/lightcurve_classes/@transitingOrbitClass/compute_transit_time.m ...
   ./astrophysics_classes/lightcurve_classes/@transitingOrbitClass/small_transit_light_curve.m ...
   ./astrophysics_classes/lightcurve_classes/@transitingPlanetClass/create_light_curve.m ...
   ./astrophysics_classes/lightcurve_classes/@transitingPlanetClass/transitingPlanetClass.m ...
    /path/to/matlab/common/mfiles/wrapper/retrieveTad.m ...
    /path/to/matlab/common/mfiles/wrapper/retrieveKics.m ...
    /path/to/matlab/common/mfiles/prf/get_prf.m ...
    -a ./configuration_files/optimizedMaskDefinitions.mat ...
    -a ./configuration_files/maskDefinitions.mat ...
    -a ./configuration_files/gcmshapes_03_16_2005.mat ...
    -a ./configuration_files/requantizationTable.mat ...
    -a ./configuration_files/jitter06a_perf_befDesat_0p5sec144hr.mat ...
    -a ./configuration_files/solnew.mat ...
    -a ./configuration_files/atlasNonlinearLimbDarkeningData.mat ...
    -a ./configuration_files/keplerInitialOrbit.mat ...
    -a ./configuration_files/vignettingData.mat
