function make_dither_params(offsets, outputFile)
%function make_dither_params(offsets, outputFile)
%
% This function uses the offsets from the specified offsets struct
% (see /path/to/ETEM_PSFs/dither_data/prfOffsetPattern.mat)
% and uses them to generate a .properties file suitable for 
% importing into the Etem2DitherParameters parameter set
%
% 
% Copyright 2017 United States Government as represented by the
% Administrator of the National Aeronautics and Space Administration.
% All Rights Reserved.
% 
% This file is available under the terms of the NASA Open Source Agreement
% (NOSA). You should have received a copy of this agreement with the
% Kepler source code; see the file NASA-OPEN-SOURCE-AGREEMENT.doc.
% 
% No Warranty: THE SUBJECT SOFTWARE IS PROVIDED "AS IS" WITHOUT ANY
% WARRANTY OF ANY KIND, EITHER EXPRESSED, IMPLIED, OR STATUTORY,
% INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY THAT THE SUBJECT SOFTWARE
% WILL CONFORM TO SPECIFICATIONS, ANY IMPLIED WARRANTIES OF
% MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR FREEDOM FROM
% INFRINGEMENT, ANY WARRANTY THAT THE SUBJECT SOFTWARE WILL BE ERROR
% FREE, OR ANY WARRANTY THAT DOCUMENTATION, IF PROVIDED, WILL CONFORM
% TO THE SUBJECT SOFTWARE. THIS AGREEMENT DOES NOT, IN ANY MANNER,
% CONSTITUTE AN ENDORSEMENT BY GOVERNMENT AGENCY OR ANY PRIOR RECIPIENT
% OF ANY RESULTS, RESULTING DESIGNS, HARDWARE, SOFTWARE PRODUCTS OR ANY
% OTHER APPLICATIONS RESULTING FROM USE OF THE SUBJECT SOFTWARE.
% FURTHER, GOVERNMENT AGENCY DISCLAIMS ALL WARRANTIES AND LIABILITIES
% REGARDING THIRD-PARTY SOFTWARE, IF PRESENT IN THE ORIGINAL SOFTWARE,
% AND DISTRIBUTES IT "AS IS."
% 
% Waiver and Indemnity: RECIPIENT AGREES TO WAIVE ANY AND ALL CLAIMS
% AGAINST THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND
% SUBCONTRACTORS, AS WELL AS ANY PRIOR RECIPIENT. IF RECIPIENT'S USE OF
% THE SUBJECT SOFTWARE RESULTS IN ANY LIABILITIES, DEMANDS, DAMAGES,
% EXPENSES OR LOSSES ARISING FROM SUCH USE, INCLUDING ANY DAMAGES FROM
% PRODUCTS BASED ON, OR RESULTING FROM, RECIPIENT'S USE OF THE SUBJECT
% SOFTWARE, RECIPIENT SHALL INDEMNIFY AND HOLD HARMLESS THE UNITED
% STATES GOVERNMENT, ITS CONTRACTORS AND SUBCONTRACTORS, AS WELL AS ANY
% PRIOR RECIPIENT, TO THE EXTENT PERMITTED BY LAW. RECIPIENT'S SOLE
% REMEDY FOR ANY SUCH MATTER SHALL BE THE IMMEDIATE, UNILATERAL
% TERMINATION OF THIS AGREEMENT.
%

raSize = size(offsets.prfRelativeRaOffset, 2);
decSize = size(offsets.prfRelativeDecOffset, 2);

if(raSize ~= decSize)
    error('offset arrays not of same length: raSize=%.0f, decSize=%.0f', raSize, decSize);
end;

c = clock;

fid = fopen(outputFile, 'w');

fprintf(fid,'# generated by make_dither_params.m\n');
fprintf(fid,'# %4.0f-%2.0f-%2.0f %2.0f:%2.0f:%2.0f\n', c);
fprintf(fid,'\n');

fprintf(fid,'doDithering=true\n');
fprintf(fid,'startCadenceNumber=1\n');
fprintf(fid,'cadencesPerOffset=2\n');
fprintf(fid,'cadenceIntervalMinutes=15\n');

fprintf(fid,'raOffsets=');
for i = 1:raSize
    fprintf(fid,'%g,', offsets.prfRelativeRaOffset(i));
end;
fprintf(fid,'\n');

fprintf(fid,'decOffsets=');
for i = 1:decSize
    fprintf(fid,'%g,', offsets.prfRelativeDecOffset(i));
end;
fprintf(fid,'\n');

fprintf(fid,'phiOffsets=');
for i = 1:raSize
    fprintf(fid,'0.0,');
end;
fprintf(fid,'\n');
