  function [x,y,z]=Q2J2000(Q)
% [x,y,z]=Q2J2000(Q)
% converts the attitude quaternion Q into the attitude of the spacecraft 
% in J2000 coordinates.
% 
% Copyright 2017 United States Government as represented by the
% Administrator of the National Aeronautics and Space Administration.
% All Rights Reserved.
% 
% This file is available under the terms of the NASA Open Source Agreement
% (NOSA). You should have received a copy of this agreement with the
% Kepler source code; see the file NASA-OPEN-SOURCE-AGREEMENT.doc.
% 
% No Warranty: THE SUBJECT SOFTWARE IS PROVIDED "AS IS" WITHOUT ANY
% WARRANTY OF ANY KIND, EITHER EXPRESSED, IMPLIED, OR STATUTORY,
% INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY THAT THE SUBJECT SOFTWARE
% WILL CONFORM TO SPECIFICATIONS, ANY IMPLIED WARRANTIES OF
% MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR FREEDOM FROM
% INFRINGEMENT, ANY WARRANTY THAT THE SUBJECT SOFTWARE WILL BE ERROR
% FREE, OR ANY WARRANTY THAT DOCUMENTATION, IF PROVIDED, WILL CONFORM
% TO THE SUBJECT SOFTWARE. THIS AGREEMENT DOES NOT, IN ANY MANNER,
% CONSTITUTE AN ENDORSEMENT BY GOVERNMENT AGENCY OR ANY PRIOR RECIPIENT
% OF ANY RESULTS, RESULTING DESIGNS, HARDWARE, SOFTWARE PRODUCTS OR ANY
% OTHER APPLICATIONS RESULTING FROM USE OF THE SUBJECT SOFTWARE.
% FURTHER, GOVERNMENT AGENCY DISCLAIMS ALL WARRANTIES AND LIABILITIES
% REGARDING THIRD-PARTY SOFTWARE, IF PRESENT IN THE ORIGINAL SOFTWARE,
% AND DISTRIBUTES IT "AS IS."
% 
% Waiver and Indemnity: RECIPIENT AGREES TO WAIVE ANY AND ALL CLAIMS
% AGAINST THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND
% SUBCONTRACTORS, AS WELL AS ANY PRIOR RECIPIENT. IF RECIPIENT'S USE OF
% THE SUBJECT SOFTWARE RESULTS IN ANY LIABILITIES, DEMANDS, DAMAGES,
% EXPENSES OR LOSSES ARISING FROM SUCH USE, INCLUDING ANY DAMAGES FROM
% PRODUCTS BASED ON, OR RESULTING FROM, RECIPIENT'S USE OF THE SUBJECT
% SOFTWARE, RECIPIENT SHALL INDEMNIFY AND HOLD HARMLESS THE UNITED
% STATES GOVERNMENT, ITS CONTRACTORS AND SUBCONTRACTORS, AS WELL AS ANY
% PRIOR RECIPIENT, TO THE EXTENT PERMITTED BY LAW. RECIPIENT'S SOLE
% REMEDY FOR ANY SUCH MATTER SHALL BE THE IMMEDIATE, UNILATERAL
% TERMINATION OF THIS AGREEMENT.
%

  Q11=Q(:,1).*Q(:,1);
  Q22=Q(:,2).*Q(:,2);
  Q33=Q(:,3).*Q(:,3);
  Q44=Q(:,4).*Q(:,4);
  Q12=2*Q(:,1).*Q(:,2);
  Q13=2*Q(:,1).*Q(:,3);
  Q14=2*Q(:,1).*Q(:,4);
  Q23=2*Q(:,2).*Q(:,3);
  Q24=2*Q(:,2).*Q(:,4);
  Q34=2*Q(:,3).*Q(:,4);

  A11=Q11-Q22-Q33+Q44;
  A12=Q12-Q34;
  A13=Q13+Q24;
  A21=Q12+Q34;
  A22=-Q11+Q22-Q33+Q44;
  A23=Q23-Q14;
  A31=Q13-Q24;
  A32=Q23+Q14;
  A33=-Q11-Q22+Q33+Q44;

  x=[Q11-Q22-Q33+Q44,  Q12+Q34,          Q13-Q24];
  y=[Q12-Q34,         -Q11+Q22-Q33+Q44,  Q23+Q14];
  z=[Q13+Q24,          Q23-Q14,         -Q11-Q22+Q33+Q44];

